/**
 * Unicode emoji database for mapping Unicode codepoints to emoji names and categories
 * This provides the data needed to auto-generate the icon registry
 */

export interface EmojiData {
  codepoint: string;
  name: string;
  category: string;
  subcategory?: string;
  keywords?: string[];
}

// Comprehensive emoji database with categories
export const emojiDatabase: Record<string, EmojiData> = {
  // Smileys & Emotion
  "1F600": { codepoint: "1F600", name: "Grinning Face", category: "emotions", keywords: ["happy", "smile", "grin"] },
  "1F601": { codepoint: "1F601", name: "Beaming Face with Smiling Eyes", category: "emotions", keywords: ["happy", "smile", "joy"] },
  "1F602": { codepoint: "1F602", name: "Face with Tears of Joy", category: "emotions", keywords: ["laugh", "happy", "cry", "joy"] },
  "1F603": { codepoint: "1F603", name: "Grinning Face with Big Eyes", category: "emotions", keywords: ["happy", "smile", "grin"] },
  "1F604": { codepoint: "1F604", name: "Smiling Face with Open Mouth", category: "emotions", keywords: ["happy", "smile", "joy"] },
  "1F605": { codepoint: "1F605", name: "Smiling Face with Open Mouth & Cold Sweat", category: "emotions", keywords: ["smile", "sweat", "relief"] },
  "1F606": { codepoint: "1F606", name: "Smiling Face with Open Mouth & Closed Eyes", category: "emotions", keywords: ["happy", "smile", "laugh"] },
  "1F609": { codepoint: "1F609", name: "Winking Face", category: "emotions", keywords: ["wink", "flirt", "smile"] },
  "1F60A": { codepoint: "1F60A", name: "Smiling Face with Smiling Eyes", category: "emotions", keywords: ["happy", "smile", "blush"] },
  "1F60B": { codepoint: "1F60B", name: "Face Savoring Food", category: "emotions", keywords: ["smile", "yum", "delicious", "food"] },
  "1F60C": { codepoint: "1F60C", name: "Relieved Face", category: "emotions", keywords: ["relief", "content", "calm"] },
  "1F60D": { codepoint: "1F60D", name: "Smiling Face with Heart-Eyes", category: "emotions", keywords: ["love", "heart", "smile", "adore"] },
  "1F60E": { codepoint: "1F60E", name: "Smiling Face with Sunglasses", category: "emotions", keywords: ["cool", "sunglasses", "smile"] },
  "1F60F": { codepoint: "1F60F", name: "Smirking Face", category: "emotions", keywords: ["smirk", "mischief", "sly"] },
  "1F610": { codepoint: "1F610", name: "Neutral Face", category: "emotions", keywords: ["neutral", "meh", "blank"] },
  "1F611": { codepoint: "1F611", name: "Expressionless Face", category: "emotions", keywords: ["blank", "expressionless", "neutral"] },
  "1F612": { codepoint: "1F612", name: "Unamused Face", category: "emotions", keywords: ["unamused", "annoyed", "meh"] },
  "1F613": { codepoint: "1F613", name: "Face with Cold Sweat", category: "emotions", keywords: ["sweat", "nervous", "worried"] },
  "1F614": { codepoint: "1F614", name: "Pensive Face", category: "emotions", keywords: ["pensive", "sad", "thoughtful"] },
  "1F615": { codepoint: "1F615", name: "Confused Face", category: "emotions", keywords: ["confused", "puzzled", "uncertain"] },
  "1F616": { codepoint: "1F616", name: "Confounded Face", category: "emotions", keywords: ["confused", "frustrated", "troubled"] },
  "1F617": { codepoint: "1F617", name: "Kissing Face", category: "emotions", keywords: ["kiss", "love", "affection"] },
  "1F618": { codepoint: "1F618", name: "Face Blowing a Kiss", category: "emotions", keywords: ["kiss", "love", "heart", "affection"] },
  "1F619": { codepoint: "1F619", name: "Kissing Face with Smiling Eyes", category: "emotions", keywords: ["kiss", "love", "smile"] },
  "1F61A": { codepoint: "1F61A", name: "Kissing Face with Closed Eyes", category: "emotions", keywords: ["kiss", "love", "closed eyes"] },
  "1F61B": { codepoint: "1F61B", name: "Face with Stuck-Out Tongue", category: "emotions", keywords: ["tongue", "playful", "silly"] },
  "1F61C": { codepoint: "1F61C", name: "Face with Stuck-Out Tongue & Winking Eye", category: "emotions", keywords: ["tongue", "wink", "playful"] },
  "1F61D": { codepoint: "1F61D", name: "Face with Stuck-Out Tongue & Closed Eyes", category: "emotions", keywords: ["tongue", "playful", "silly"] },
  "1F61E": { codepoint: "1F61E", name: "Disappointed Face", category: "emotions", keywords: ["disappointed", "sad", "upset"] },
  "1F61F": { codepoint: "1F61F", name: "Worried Face", category: "emotions", keywords: ["worried", "concerned", "anxious"] },
  "1F620": { codepoint: "1F620", name: "Angry Face", category: "emotions", keywords: ["angry", "mad", "upset"] },
  "1F621": { codepoint: "1F621", name: "Pouting Face", category: "emotions", keywords: ["angry", "pout", "mad"] },
  "1F622": { codepoint: "1F622", name: "Crying Face", category: "emotions", keywords: ["cry", "sad", "tears"] },
  "1F623": { codepoint: "1F623", name: "Persevering Face", category: "emotions", keywords: ["persevere", "struggle", "determined"] },
  "1F624": { codepoint: "1F624", name: "Face with Steam From Nose", category: "emotions", keywords: ["angry", "frustrated", "steam"] },
  "1F625": { codepoint: "1F625", name: "Sad but Relieved Face", category: "emotions", keywords: ["sad", "relief", "disappointed"] },
  "1F626": { codepoint: "1F626", name: "Frowning Face with Open Mouth", category: "emotions", keywords: ["frown", "surprised", "shocked"] },
  "1F627": { codepoint: "1F627", name: "Anguished Face", category: "emotions", keywords: ["anguish", "pain", "distress"] },
  "1F628": { codepoint: "1F628", name: "Fearful Face", category: "emotions", keywords: ["fear", "scared", "afraid"] },
  "1F629": { codepoint: "1F629", name: "Weary Face", category: "emotions", keywords: ["tired", "weary", "exhausted"] },
  "1F62A": { codepoint: "1F62A", name: "Sleepy Face", category: "emotions", keywords: ["sleepy", "tired", "drowsy"] },
  "1F62B": { codepoint: "1F62B", name: "Tired Face", category: "emotions", keywords: ["tired", "exhausted", "weary"] },
  "1F62C": { codepoint: "1F62C", name: "Grimacing Face", category: "emotions", keywords: ["grimace", "awkward", "uncomfortable"] },
  "1F62D": { codepoint: "1F62D", name: "Loudly Crying Face", category: "emotions", keywords: ["cry", "sob", "tears", "sad"] },
  "1F62E": { codepoint: "1F62E", name: "Face with Open Mouth", category: "emotions", keywords: ["surprise", "shock", "amazed"] },
  "1F62F": { codepoint: "1F62F", name: "Hushed Face", category: "emotions", keywords: ["quiet", "whisper", "secret"] },
  "1F630": { codepoint: "1F630", name: "Anxious Face with Sweat", category: "emotions", keywords: ["anxious", "nervous", "sweat"] },
  "1F631": { codepoint: "1F631", name: "Face Screaming in Fear", category: "emotions", keywords: ["scream", "fear", "shock"] },
  "1F632": { codepoint: "1F632", name: "Astonished Face", category: "emotions", keywords: ["astonished", "surprised", "amazed"] },
  "1F633": { codepoint: "1F633", name: "Flushed Face", category: "emotions", keywords: ["flushed", "embarrassed", "blush"] },
  "1F634": { codepoint: "1F634", name: "Sleeping Face", category: "emotions", keywords: ["sleep", "zzz", "tired"] },
  "1F635": { codepoint: "1F635", name: "Dizzy Face", category: "emotions", keywords: ["dizzy", "confused", "spiral"] },
  "1F636": { codepoint: "1F636", name: "Face Without Mouth", category: "emotions", keywords: ["silent", "quiet", "speechless"] },
  "1F637": { codepoint: "1F637", name: "Face with Medical Mask", category: "emotions", keywords: ["mask", "sick", "medical", "health"] },
  
  // Animals & Nature
  "1F400": { codepoint: "1F400", name: "Rat", category: "animals", keywords: ["rat", "mouse", "rodent"] },
  "1F401": { codepoint: "1F401", name: "Mouse", category: "animals", keywords: ["mouse", "rodent", "small"] },
  "1F402": { codepoint: "1F402", name: "Ox", category: "animals", keywords: ["ox", "bull", "cattle"] },
  "1F403": { codepoint: "1F403", name: "Water Buffalo", category: "animals", keywords: ["buffalo", "water", "animal"] },
  "1F404": { codepoint: "1F404", name: "Cow", category: "animals", keywords: ["cow", "cattle", "milk"] },
  "1F405": { codepoint: "1F405", name: "Tiger", category: "animals", keywords: ["tiger", "cat", "wild"] },
  "1F406": { codepoint: "1F406", name: "Leopard", category: "animals", keywords: ["leopard", "cat", "spots"] },
  "1F407": { codepoint: "1F407", name: "Rabbit", category: "animals", keywords: ["rabbit", "bunny", "hop"] },
  "1F408": { codepoint: "1F408", name: "Cat", category: "animals", keywords: ["cat", "kitten", "feline"] },
  "1F409": { codepoint: "1F409", name: "Dragon", category: "animals", keywords: ["dragon", "mythical", "fantasy"] },
  "1F40A": { codepoint: "1F40A", name: "Crocodile", category: "animals", keywords: ["crocodile", "alligator", "reptile"] },
  "1F40B": { codepoint: "1F40B", name: "Whale", category: "animals", keywords: ["whale", "ocean", "marine"] },
  "1F40C": { codepoint: "1F40C", name: "Snail", category: "animals", keywords: ["snail", "slow", "shell"] },
  "1F40D": { codepoint: "1F40D", name: "Snake", category: "animals", keywords: ["snake", "serpent", "reptile"] },
  "1F40E": { codepoint: "1F40E", name: "Horse", category: "animals", keywords: ["horse", "equine", "stallion"] },
  "1F40F": { codepoint: "1F40F", name: "Ram", category: "animals", keywords: ["ram", "sheep", "horns"] },
  "1F410": { codepoint: "1F410", name: "Goat", category: "animals", keywords: ["goat", "animal", "farm"] },
  "1F411": { codepoint: "1F411", name: "Sheep", category: "animals", keywords: ["sheep", "wool", "farm"] },
  "1F412": { codepoint: "1F412", name: "Monkey", category: "animals", keywords: ["monkey", "primate", "banana"] },
  "1F413": { codepoint: "1F413", name: "Rooster", category: "animals", keywords: ["rooster", "chicken", "bird"] },
  "1F414": { codepoint: "1F414", name: "Chicken", category: "animals", keywords: ["chicken", "bird", "farm"] },
  "1F415": { codepoint: "1F415", name: "Dog", category: "animals", keywords: ["dog", "puppy", "pet"] },
  "1F416": { codepoint: "1F416", name: "Pig", category: "animals", keywords: ["pig", "pork", "farm"] },
  "1F417": { codepoint: "1F417", name: "Boar", category: "animals", keywords: ["boar", "wild pig", "animal"] },
  "1F418": { codepoint: "1F418", name: "Elephant", category: "animals", keywords: ["elephant", "trunk", "large"] },
  "1F419": { codepoint: "1F419", name: "Octopus", category: "animals", keywords: ["octopus", "tentacles", "sea"] },
  "1F41A": { codepoint: "1F41A", name: "Spiral Shell", category: "animals", keywords: ["shell", "spiral", "ocean"] },
  "1F41B": { codepoint: "1F41B", name: "Bug", category: "animals", keywords: ["bug", "insect", "beetle"] },
  "1F41C": { codepoint: "1F41C", name: "Ant", category: "animals", keywords: ["ant", "insect", "work"] },
  "1F41D": { codepoint: "1F41D", name: "Honeybee", category: "animals", keywords: ["bee", "honey", "buzz"] },
  "1F41E": { codepoint: "1F41E", name: "Lady Beetle", category: "animals", keywords: ["ladybug", "beetle", "insect"] },
  "1F41F": { codepoint: "1F41F", name: "Fish", category: "animals", keywords: ["fish", "ocean", "swim"] },
  "1F420": { codepoint: "1F420", name: "Tropical Fish", category: "animals", keywords: ["fish", "tropical", "colorful"] },
  "1F421": { codepoint: "1F421", name: "Blowfish", category: "animals", keywords: ["blowfish", "pufferfish", "spiky"] },
  "1F422": { codepoint: "1F422", name: "Turtle", category: "animals", keywords: ["turtle", "slow", "shell"] },
  "1F423": { codepoint: "1F423", name: "Hatching Chick", category: "animals", keywords: ["chick", "hatching", "egg"] },
  "1F424": { codepoint: "1F424", name: "Baby Chick", category: "animals", keywords: ["chick", "baby", "cute"] },
  "1F425": { codepoint: "1F425", name: "Front-Facing Baby Chick", category: "animals", keywords: ["chick", "baby", "front"] },
  "1F426": { codepoint: "1F426", name: "Bird", category: "animals", keywords: ["bird", "fly", "tweet"] },
  "1F427": { codepoint: "1F427", name: "Penguin", category: "animals", keywords: ["penguin", "cold", "antarctica"] },
  "1F428": { codepoint: "1F428", name: "Koala", category: "animals", keywords: ["koala", "australia", "eucalyptus"] },
  "1F429": { codepoint: "1F429", name: "Poodle", category: "animals", keywords: ["poodle", "dog", "fluffy"] },
  "1F42A": { codepoint: "1F42A", name: "Dromedary Camel", category: "animals", keywords: ["camel", "desert", "hump"] },
  "1F42B": { codepoint: "1F42B", name: "Bactrian Camel", category: "animals", keywords: ["camel", "two humps", "desert"] },
  "1F42C": { codepoint: "1F42C", name: "Dolphin", category: "animals", keywords: ["dolphin", "smart", "ocean"] },
  "1F42D": { codepoint: "1F42D", name: "Mouse Face", category: "animals", keywords: ["mouse", "face", "rodent"] },
  "1F42E": { codepoint: "1F42E", name: "Cow Face", category: "animals", keywords: ["cow", "face", "moo"] },
  "1F42F": { codepoint: "1F42F", name: "Tiger Face", category: "animals", keywords: ["tiger", "face", "stripes"] },
  "1F430": { codepoint: "1F430", name: "Rabbit Face", category: "animals", keywords: ["rabbit", "face", "bunny"] },
  "1F431": { codepoint: "1F431", name: "Cat Face", category: "animals", keywords: ["cat", "face", "meow"] },
  "1F432": { codepoint: "1F432", name: "Dragon Face", category: "animals", keywords: ["dragon", "face", "mythical"] },
  "1F433": { codepoint: "1F433", name: "Spouting Whale", category: "animals", keywords: ["whale", "spout", "ocean"] },
  "1F434": { codepoint: "1F434", name: "Horse Face", category: "animals", keywords: ["horse", "face", "neigh"] },
  "1F435": { codepoint: "1F435", name: "Monkey Face", category: "animals", keywords: ["monkey", "face", "primate"] },
  "1F436": { codepoint: "1F436", name: "Dog Face", category: "animals", keywords: ["dog", "face", "woof"] },
  "1F437": { codepoint: "1F437", name: "Pig Face", category: "animals", keywords: ["pig", "face", "oink"] },
  "1F438": { codepoint: "1F438", name: "Frog Face", category: "animals", keywords: ["frog", "face", "ribbit"] },
  "1F439": { codepoint: "1F439", name: "Hamster Face", category: "animals", keywords: ["hamster", "face", "cheeks"] },
  "1F43A": { codepoint: "1F43A", name: "Wolf Face", category: "animals", keywords: ["wolf", "face", "howl"] },
  "1F43B": { codepoint: "1F43B", name: "Bear Face", category: "animals", keywords: ["bear", "face", "roar"] },
  "1F43C": { codepoint: "1F43C", name: "Panda Face", category: "animals", keywords: ["panda", "face", "bamboo"] },
  "1F43D": { codepoint: "1F43D", name: "Pig Nose", category: "animals", keywords: ["pig", "nose", "snout"] },
  "1F43E": { codepoint: "1F43E", name: "Paw Prints", category: "animals", keywords: ["paw", "prints", "animal"] },

  // Food & Drink
  "1F32D": { codepoint: "1F32D", name: "Hot Dog", category: "food", keywords: ["hot dog", "sausage", "food"] },
  "1F32E": { codepoint: "1F32E", name: "Taco", category: "food", keywords: ["taco", "mexican", "food"] },
  "1F32F": { codepoint: "1F32F", name: "Burrito", category: "food", keywords: ["burrito", "mexican", "wrap"] },
  "1F330": { codepoint: "1F330", name: "Chestnut", category: "food", keywords: ["chestnut", "nut", "autumn"] },
  "1F331": { codepoint: "1F331", name: "Seedling", category: "nature", keywords: ["seedling", "plant", "grow"] },
  "1F332": { codepoint: "1F332", name: "Evergreen Tree", category: "nature", keywords: ["tree", "evergreen", "pine"] },
  "1F333": { codepoint: "1F333", name: "Deciduous Tree", category: "nature", keywords: ["tree", "deciduous", "leaves"] },
  "1F334": { codepoint: "1F334", name: "Palm Tree", category: "nature", keywords: ["palm", "tree", "tropical"] },
  "1F335": { codepoint: "1F335", name: "Cactus", category: "nature", keywords: ["cactus", "desert", "spiky"] },
  "1F336": { codepoint: "1F336", name: "Hot Pepper", category: "food", keywords: ["pepper", "hot", "spicy"] },
  "1F337": { codepoint: "1F337", name: "Tulip", category: "nature", keywords: ["tulip", "flower", "spring"] },
  "1F338": { codepoint: "1F338", name: "Cherry Blossom", category: "nature", keywords: ["cherry", "blossom", "pink"] },
  "1F339": { codepoint: "1F339", name: "Rose", category: "nature", keywords: ["rose", "flower", "love"] },
  "1F33A": { codepoint: "1F33A", name: "Hibiscus", category: "nature", keywords: ["hibiscus", "flower", "tropical"] },
  "1F33B": { codepoint: "1F33B", name: "Sunflower", category: "nature", keywords: ["sunflower", "yellow", "sunny"] },
  "1F33C": { codepoint: "1F33C", name: "Blossom", category: "nature", keywords: ["blossom", "flower", "bloom"] },
  "1F33D": { codepoint: "1F33D", name: "Ear of Corn", category: "food", keywords: ["corn", "maize", "vegetable"] },
  "1F33E": { codepoint: "1F33E", name: "Sheaf of Rice", category: "food", keywords: ["rice", "grain", "harvest"] },
  "1F33F": { codepoint: "1F33F", name: "Herb", category: "nature", keywords: ["herb", "plant", "green"] },
  "1F340": { codepoint: "1F340", name: "Four Leaf Clover", category: "nature", keywords: ["clover", "luck", "four leaf"] },
  "1F341": { codepoint: "1F341", name: "Maple Leaf", category: "nature", keywords: ["maple", "leaf", "autumn"] },
  "1F342": { codepoint: "1F342", name: "Fallen Leaves", category: "nature", keywords: ["leaves", "fallen", "autumn"] },
  "1F343": { codepoint: "1F343", name: "Leaf Fluttering in Wind", category: "nature", keywords: ["leaf", "wind", "flutter"] },
  "1F344": { codepoint: "1F344", name: "Mushroom", category: "food", keywords: ["mushroom", "fungi", "food"] },
  "1F345": { codepoint: "1F345", name: "Tomato", category: "food", keywords: ["tomato", "red", "vegetable"] },
  "1F346": { codepoint: "1F346", name: "Eggplant", category: "food", keywords: ["eggplant", "aubergine", "purple"] },
  "1F347": { codepoint: "1F347", name: "Grapes", category: "food", keywords: ["grapes", "wine", "fruit"] },
  "1F348": { codepoint: "1F348", name: "Melon", category: "food", keywords: ["melon", "cantaloupe", "fruit"] },
  "1F349": { codepoint: "1F349", name: "Watermelon", category: "food", keywords: ["watermelon", "summer", "fruit", "juicy", "red"] },
  "1F34A": { codepoint: "1F34A", name: "Tangerine", category: "food", keywords: ["tangerine", "orange", "citrus"] },
  "1F34B": { codepoint: "1F34B", name: "Lemon", category: "food", keywords: ["lemon", "yellow", "citrus", "sour"] },
  "1F34C": { codepoint: "1F34C", name: "Banana", category: "food", keywords: ["banana", "yellow", "fruit", "monkey"] },
  "1F34D": { codepoint: "1F34D", name: "Pineapple", category: "food", keywords: ["pineapple", "tropical", "fruit", "sweet"] },
  "1F34E": { codepoint: "1F34E", name: "Red Apple", category: "food", keywords: ["apple", "red", "fruit", "healthy"] },
  "1F34F": { codepoint: "1F34F", name: "Green Apple", category: "food", keywords: ["apple", "green", "fruit", "healthy"] },
  "1F350": { codepoint: "1F350", name: "Pear", category: "food", keywords: ["pear", "fruit", "green"] },
  "1F351": { codepoint: "1F351", name: "Peach", category: "food", keywords: ["peach", "fruit", "fuzzy"] },
  "1F352": { codepoint: "1F352", name: "Cherries", category: "food", keywords: ["cherries", "red", "fruit", "sweet"] },
  "1F353": { codepoint: "1F353", name: "Strawberry", category: "food", keywords: ["strawberry", "red", "fruit", "berry"] },
  "1F354": { codepoint: "1F354", name: "Hamburger", category: "food", keywords: ["hamburger", "burger", "fast food"] },
  "1F355": { codepoint: "1F355", name: "Pizza", category: "food", keywords: ["pizza", "italian", "cheese", "slice"] },
  "1F356": { codepoint: "1F356", name: "Meat on Bone", category: "food", keywords: ["meat", "bone", "food"] },
  "1F357": { codepoint: "1F357", name: "Poultry Leg", category: "food", keywords: ["chicken", "leg", "meat"] },
  "1F358": { codepoint: "1F358", name: "Rice Cracker", category: "food", keywords: ["rice", "cracker", "japanese"] },
  "1F359": { codepoint: "1F359", name: "Rice Ball", category: "food", keywords: ["rice", "ball", "japanese"] },
  "1F35A": { codepoint: "1F35A", name: "Cooked Rice", category: "food", keywords: ["rice", "cooked", "bowl"] },
  "1F35B": { codepoint: "1F35B", name: "Curry Rice", category: "food", keywords: ["curry", "rice", "spicy"] },
  "1F35C": { codepoint: "1F35C", name: "Steaming Bowl", category: "food", keywords: ["bowl", "steaming", "hot"] },
  "1F35D": { codepoint: "1F35D", name: "Spaghetti", category: "food", keywords: ["spaghetti", "pasta", "italian"] },
  "1F35E": { codepoint: "1F35E", name: "Bread", category: "food", keywords: ["bread", "loaf", "baked"] },
  "1F35F": { codepoint: "1F35F", name: "French Fries", category: "food", keywords: ["fries", "french", "potato"] },
  "1F360": { codepoint: "1F360", name: "Roasted Sweet Potato", category: "food", keywords: ["sweet potato", "roasted", "vegetable"] },
  "1F361": { codepoint: "1F361", name: "Dango", category: "food", keywords: ["dango", "japanese", "sweet"] },
  "1F362": { codepoint: "1F362", name: "Oden", category: "food", keywords: ["oden", "japanese", "hot pot"] },
  "1F363": { codepoint: "1F363", name: "Sushi", category: "food", keywords: ["sushi", "japanese", "fish"] },
  "1F364": { codepoint: "1F364", name: "Fried Shrimp", category: "food", keywords: ["shrimp", "fried", "seafood"] },
  "1F365": { codepoint: "1F365", name: "Fish Cake with Swirl", category: "food", keywords: ["fish cake", "swirl", "japanese"] },
  "1F366": { codepoint: "1F366", name: "Soft Ice Cream", category: "food", keywords: ["ice cream", "soft serve", "sweet"] },
  "1F367": { codepoint: "1F367", name: "Shaved Ice", category: "food", keywords: ["shaved ice", "cold", "sweet"] },
  "1F368": { codepoint: "1F368", name: "Ice Cream", category: "food", keywords: ["ice cream", "cold", "sweet"] },
  "1F369": { codepoint: "1F369", name: "Doughnut", category: "food", keywords: ["donut", "doughnut", "sweet"] },
  "1F36A": { codepoint: "1F36A", name: "Cookie", category: "food", keywords: ["cookie", "sweet", "baked"] },
  "1F36B": { codepoint: "1F36B", name: "Chocolate Bar", category: "food", keywords: ["chocolate", "bar", "sweet"] },
  "1F36C": { codepoint: "1F36C", name: "Candy", category: "food", keywords: ["candy", "sweet", "treat"] },
  "1F36D": { codepoint: "1F36D", name: "Lollipop", category: "food", keywords: ["lollipop", "candy", "sweet"] },
  "1F36E": { codepoint: "1F36E", name: "Custard", category: "food", keywords: ["custard", "pudding", "sweet"] },
  "1F36F": { codepoint: "1F36F", name: "Honey Pot", category: "food", keywords: ["honey", "pot", "sweet", "bee"] },
  "1F370": { codepoint: "1F370", name: "Shortcake", category: "food", keywords: ["cake", "shortcake", "sweet"] },
  "1F371": { codepoint: "1F371", name: "Bento Box", category: "food", keywords: ["bento", "japanese", "lunch"] },
  "1F372": { codepoint: "1F372", name: "Pot of Food", category: "food", keywords: ["pot", "stew", "cooking"] },
  "1F373": { codepoint: "1F373", name: "Cooking", category: "food", keywords: ["cooking", "frying pan", "egg"] },
  "1F374": { codepoint: "1F374", name: "Fork and Knife", category: "objects", keywords: ["fork", "knife", "utensils"] },
  "1F375": { codepoint: "1F375", name: "Teacup Without Handle", category: "food", keywords: ["tea", "cup", "drink"] },
  "1F376": { codepoint: "1F376", name: "Sake", category: "food", keywords: ["sake", "japanese", "alcohol"] },
  "1F377": { codepoint: "1F377", name: "Wine Glass", category: "food", keywords: ["wine", "glass", "alcohol"] },
  "1F378": { codepoint: "1F378", name: "Cocktail Glass", category: "food", keywords: ["cocktail", "drink", "alcohol"] },
  "1F379": { codepoint: "1F379", name: "Tropical Drink", category: "food", keywords: ["tropical", "drink", "cocktail"] },
  "1F37A": { codepoint: "1F37A", name: "Beer Mug", category: "food", keywords: ["beer", "mug", "alcohol"] },
  "1F37B": { codepoint: "1F37B", name: "Clinking Beer Mugs", category: "food", keywords: ["beer", "cheers", "celebration"] },
  "1F37C": { codepoint: "1F37C", name: "Baby Bottle", category: "objects", keywords: ["baby", "bottle", "milk"] },

  // Travel & Places
  "1F680": { codepoint: "1F680", name: "Rocket", category: "travel", keywords: ["rocket", "space", "launch"] },
  "1F681": { codepoint: "1F681", name: "Helicopter", category: "travel", keywords: ["helicopter", "aircraft", "fly"] },
  "1F682": { codepoint: "1F682", name: "Locomotive", category: "travel", keywords: ["train", "locomotive", "transport"] },
  "1F683": { codepoint: "1F683", name: "Railway Car", category: "travel", keywords: ["train", "car", "railway"] },
  "1F684": { codepoint: "1F684", name: "High-Speed Train", category: "travel", keywords: ["train", "fast", "bullet"] },
  "1F685": { codepoint: "1F685", name: "High-Speed Train with Bullet Nose", category: "travel", keywords: ["train", "bullet", "fast"] },
  "1F686": { codepoint: "1F686", name: "Train", category: "travel", keywords: ["train", "transport", "railway"] },
  "1F687": { codepoint: "1F687", name: "Metro", category: "travel", keywords: ["metro", "subway", "underground"] },
  "1F688": { codepoint: "1F688", name: "Light Rail", category: "travel", keywords: ["light rail", "train", "transport"] },
  "1F689": { codepoint: "1F689", name: "Station", category: "travel", keywords: ["station", "train", "transport"] },
  "1F68A": { codepoint: "1F68A", name: "Tram", category: "travel", keywords: ["tram", "trolley", "transport"] },
  "1F68B": { codepoint: "1F68B", name: "Tram Car", category: "travel", keywords: ["tram", "car", "transport"] },
  "1F68C": { codepoint: "1F68C", name: "Bus", category: "travel", keywords: ["bus", "transport", "public"] },
  "1F68D": { codepoint: "1F68D", name: "Oncoming Bus", category: "travel", keywords: ["bus", "oncoming", "transport"] },
  "1F68E": { codepoint: "1F68E", name: "Trolleybus", category: "travel", keywords: ["trolleybus", "electric", "transport"] },
  "1F68F": { codepoint: "1F68F", name: "Bus Stop", category: "travel", keywords: ["bus stop", "waiting", "transport"] },
  "1F690": { codepoint: "1F690", name: "Minibus", category: "travel", keywords: ["minibus", "small", "transport"] },
  "1F691": { codepoint: "1F691", name: "Ambulance", category: "travel", keywords: ["ambulance", "emergency", "medical"] },
  "1F692": { codepoint: "1F692", name: "Fire Engine", category: "travel", keywords: ["fire engine", "emergency", "rescue"] },
  "1F693": { codepoint: "1F693", name: "Police Car", category: "travel", keywords: ["police", "car", "law"] },
  "1F694": { codepoint: "1F694", name: "Oncoming Police Car", category: "travel", keywords: ["police", "oncoming", "emergency"] },
  "1F695": { codepoint: "1F695", name: "Taxi", category: "travel", keywords: ["taxi", "cab", "transport"] },
  "1F696": { codepoint: "1F696", name: "Oncoming Taxi", category: "travel", keywords: ["taxi", "oncoming", "transport"] },
  "1F697": { codepoint: "1F697", name: "Automobile", category: "travel", keywords: ["car", "automobile", "vehicle"] },
  "1F698": { codepoint: "1F698", name: "Oncoming Automobile", category: "travel", keywords: ["car", "oncoming", "vehicle"] },
  "1F699": { codepoint: "1F699", name: "Sport Utility Vehicle", category: "travel", keywords: ["suv", "car", "vehicle"] },
  "1F69A": { codepoint: "1F69A", name: "Delivery Truck", category: "travel", keywords: ["truck", "delivery", "transport"] },
  "1F69B": { codepoint: "1F69B", name: "Articulated Lorry", category: "travel", keywords: ["truck", "lorry", "transport"] },
  "1F69C": { codepoint: "1F69C", name: "Tractor", category: "travel", keywords: ["tractor", "farm", "agriculture"] },
  "1F69D": { codepoint: "1F69D", name: "Monorail", category: "travel", keywords: ["monorail", "train", "elevated"] },
  "1F69E": { codepoint: "1F69E", name: "Mountain Railway", category: "travel", keywords: ["railway", "mountain", "scenic"] },
  "1F69F": { codepoint: "1F69F", name: "Suspension Railway", category: "travel", keywords: ["railway", "suspension", "hanging"] },
  "1F6A0": { codepoint: "1F6A0", name: "Mountain Cableway", category: "travel", keywords: ["cableway", "mountain", "ski"] },
  "1F6A1": { codepoint: "1F6A1", name: "Aerial Tramway", category: "travel", keywords: ["tramway", "aerial", "cable"] },
  "1F6A2": { codepoint: "1F6A2", name: "Ship", category: "travel", keywords: ["ship", "boat", "ocean"] },
  "1F6A3": { codepoint: "1F6A3", name: "Rowboat", category: "travel", keywords: ["rowboat", "rowing", "water"] },
  "1F6A4": { codepoint: "1F6A4", name: "Speedboat", category: "travel", keywords: ["speedboat", "fast", "water"] },
  "1F6A5": { codepoint: "1F6A5", name: "Horizontal Traffic Light", category: "travel", keywords: ["traffic light", "horizontal", "stop"] },
  "1F6A6": { codepoint: "1F6A6", name: "Vertical Traffic Light", category: "travel", keywords: ["traffic light", "vertical", "stop"] },
  "1F6A7": { codepoint: "1F6A7", name: "Construction", category: "travel", keywords: ["construction", "work", "caution"] },
  "1F6A8": { codepoint: "1F6A8", name: "Police Car Light", category: "travel", keywords: ["police", "light", "emergency"] },
  "1F6A9": { codepoint: "1F6A9", name: "Triangular Flag", category: "objects", keywords: ["flag", "triangular", "banner"] },
  "1F6AA": { codepoint: "1F6AA", name: "Door", category: "objects", keywords: ["door", "entrance", "exit"] },
  "1F6AB": { codepoint: "1F6AB", name: "No Entry Sign", category: "symbols", keywords: ["no entry", "forbidden", "stop"] },
  "1F6AC": { codepoint: "1F6AC", name: "Cigarette", category: "objects", keywords: ["cigarette", "smoking", "tobacco"] },
  "1F6AD": { codepoint: "1F6AD", name: "No Smoking", category: "symbols", keywords: ["no smoking", "forbidden", "health"] },
  "1F6AE": { codepoint: "1F6AE", name: "Litter in Bin Sign", category: "symbols", keywords: ["litter", "trash", "clean"] },
  "1F6AF": { codepoint: "1F6AF", name: "Do Not Litter", category: "symbols", keywords: ["no litter", "clean", "environment"] },
  "1F6B0": { codepoint: "1F6B0", name: "Potable Water", category: "symbols", keywords: ["water", "drinking", "potable"] },
  "1F6B1": { codepoint: "1F6B1", name: "Non-Potable Water", category: "symbols", keywords: ["water", "non-potable", "not drinking"] },
  "1F6B2": { codepoint: "1F6B2", name: "Bicycle", category: "travel", keywords: ["bicycle", "bike", "cycle"] },
  "1F6B3": { codepoint: "1F6B3", name: "No Bicycles", category: "symbols", keywords: ["no bicycles", "forbidden", "bike"] },

  // Objects
  "1F4A0": { codepoint: "1F4A0", name: "Diamond with a Dot", category: "symbols", keywords: ["diamond", "dot", "shape"] },
  "1F4A1": { codepoint: "1F4A1", name: "Light Bulb", category: "objects", keywords: ["light bulb", "idea", "bright"] },
  "1F4A2": { codepoint: "1F4A2", name: "Anger Symbol", category: "symbols", keywords: ["anger", "mad", "symbol"] },
  "1F4A3": { codepoint: "1F4A3", name: "Bomb", category: "objects", keywords: ["bomb", "explosive", "danger"] },
  "1F4A4": { codepoint: "1F4A4", name: "Zzz", category: "symbols", keywords: ["sleep", "zzz", "tired"] },
  "1F4A5": { codepoint: "1F4A5", name: "Collision", category: "symbols", keywords: ["collision", "boom", "crash"] },
  "1F4A6": { codepoint: "1F4A6", name: "Sweat Droplets", category: "symbols", keywords: ["sweat", "water", "droplets"] },
  "1F4A7": { codepoint: "1F4A7", name: "Droplet", category: "symbols", keywords: ["water", "droplet", "liquid"] },
  "1F4A8": { codepoint: "1F4A8", name: "Dashing Away", category: "symbols", keywords: ["dash", "speed", "fast"] },
  "1F4A9": { codepoint: "1F4A9", name: "Pile of Poo", category: "symbols", keywords: ["poop", "pile", "smiling"] },
  "1F4AA": { codepoint: "1F4AA", name: "Flexed Biceps", category: "symbols", keywords: ["muscle", "strong", "flex"] },
  "1F4AB": { codepoint: "1F4AB", name: "Dizzy", category: "symbols", keywords: ["dizzy", "stars", "confused"] },
  "1F4AC": { codepoint: "1F4AC", name: "Speech Balloon", category: "symbols", keywords: ["speech", "balloon", "talk"] },
  "1F4AD": { codepoint: "1F4AD", name: "Thought Balloon", category: "symbols", keywords: ["thought", "balloon", "think"] },
  "1F4AE": { codepoint: "1F4AE", name: "White Flower", category: "symbols", keywords: ["flower", "white", "japanese"] },
  "1F4AF": { codepoint: "1F4AF", name: "Hundred Points", category: "symbols", keywords: ["hundred", "100", "perfect"] },

  // Flags (Regional Indicators)
  "1F1E6": { codepoint: "1F1E6", name: "Regional Indicator Symbol Letter A", category: "flags", keywords: ["flag", "letter", "a"] },
  "1F1E7": { codepoint: "1F1E7", name: "Regional Indicator Symbol Letter B", category: "flags", keywords: ["flag", "letter", "b"] },
  "1F1E8": { codepoint: "1F1E8", name: "Regional Indicator Symbol Letter C", category: "flags", keywords: ["flag", "letter", "c"] },
  "1F1E9": { codepoint: "1F1E9", name: "Regional Indicator Symbol Letter D", category: "flags", keywords: ["flag", "letter", "d"] },
  "1F1EA": { codepoint: "1F1EA", name: "Regional Indicator Symbol Letter E", category: "flags", keywords: ["flag", "letter", "e"] },
  "1F1EB": { codepoint: "1F1EB", name: "Regional Indicator Symbol Letter F", category: "flags", keywords: ["flag", "letter", "f"] },
  "1F1EC": { codepoint: "1F1EC", name: "Regional Indicator Symbol Letter G", category: "flags", keywords: ["flag", "letter", "g"] },
  "1F1ED": { codepoint: "1F1ED", name: "Regional Indicator Symbol Letter H", category: "flags", keywords: ["flag", "letter", "h"] },
  "1F1EE": { codepoint: "1F1EE", name: "Regional Indicator Symbol Letter I", category: "flags", keywords: ["flag", "letter", "i"] },
  "1F1EF": { codepoint: "1F1EF", name: "Regional Indicator Symbol Letter J", category: "flags", keywords: ["flag", "letter", "j"] },
  "1F1F0": { codepoint: "1F1F0", name: "Regional Indicator Symbol Letter K", category: "flags", keywords: ["flag", "letter", "k"] },
  "1F1F1": { codepoint: "1F1F1", name: "Regional Indicator Symbol Letter L", category: "flags", keywords: ["flag", "letter", "l"] },
  "1F1F2": { codepoint: "1F1F2", name: "Regional Indicator Symbol Letter M", category: "flags", keywords: ["flag", "letter", "m"] },
  "1F1F3": { codepoint: "1F1F3", name: "Regional Indicator Symbol Letter N", category: "flags", keywords: ["flag", "letter", "n"] },
  "1F1F4": { codepoint: "1F1F4", name: "Regional Indicator Symbol Letter O", category: "flags", keywords: ["flag", "letter", "o"] },
  "1F1F5": { codepoint: "1F1F5", name: "Regional Indicator Symbol Letter P", category: "flags", keywords: ["flag", "letter", "p"] },
  "1F1F6": { codepoint: "1F1F6", name: "Regional Indicator Symbol Letter Q", category: "flags", keywords: ["flag", "letter", "q"] },
  "1F1F7": { codepoint: "1F1F7", name: "Regional Indicator Symbol Letter R", category: "flags", keywords: ["flag", "letter", "r"] },
  "1F1F8": { codepoint: "1F1F8", name: "Regional Indicator Symbol Letter S", category: "flags", keywords: ["flag", "letter", "s"] },
  "1F1F9": { codepoint: "1F1F9", name: "Regional Indicator Symbol Letter T", category: "flags", keywords: ["flag", "letter", "t"] },
  "1F1FA": { codepoint: "1F1FA", name: "Regional Indicator Symbol Letter U", category: "flags", keywords: ["flag", "letter", "u"] },
  "1F1FB": { codepoint: "1F1FB", name: "Regional Indicator Symbol Letter V", category: "flags", keywords: ["flag", "letter", "v"] },
  "1F1FC": { codepoint: "1F1FC", name: "Regional Indicator Symbol Letter W", category: "flags", keywords: ["flag", "letter", "w"] },
  "1F1FD": { codepoint: "1F1FD", name: "Regional Indicator Symbol Letter X", category: "flags", keywords: ["flag", "letter", "x"] },
  "1F1FE": { codepoint: "1F1FE", name: "Regional Indicator Symbol Letter Y", category: "flags", keywords: ["flag", "letter", "y"] },
  "1F1FF": { codepoint: "1F1FF", name: "Regional Indicator Symbol Letter Z", category: "flags", keywords: ["flag", "letter", "z"] },

  // Sports & Activities
  "26BD": { codepoint: "26BD", name: "Soccer Ball", category: "sports", keywords: ["soccer", "football", "ball", "sport"] },
  "26BE": { codepoint: "26BE", name: "Baseball", category: "sports", keywords: ["baseball", "ball", "sport"] },
  "1F3C0": { codepoint: "1F3C0", name: "Basketball", category: "sports", keywords: ["basketball", "ball", "sport"] },
  "1F3C8": { codepoint: "1F3C8", name: "American Football", category: "sports", keywords: ["football", "american", "ball", "sport"] },
  "1F3C9": { codepoint: "1F3C9", name: "Rugby Football", category: "sports", keywords: ["rugby", "football", "ball", "sport"] },
  "1F3BE": { codepoint: "1F3BE", name: "Tennis", category: "sports", keywords: ["tennis", "ball", "racket", "sport"] },
  "1F3BF": { codepoint: "1F3BF", name: "Ski", category: "sports", keywords: ["ski", "snow", "winter", "sport"] },
  "1F3C1": { codepoint: "1F3C1", name: "Chequered Flag", category: "sports", keywords: ["flag", "racing", "finish", "checkered"] },
  "1F3C5": { codepoint: "1F3C5", name: "Sports Medal", category: "sports", keywords: ["medal", "sports", "winner", "gold"] },
  "1F3C6": { codepoint: "1F3C6", name: "Trophy", category: "sports", keywords: ["trophy", "winner", "champion", "gold"] },

  // Nature & Weather
  "2600": { codepoint: "2600", name: "Sun", category: "nature", keywords: ["sun", "sunny", "bright", "weather"] },
  "2601": { codepoint: "2601", name: "Cloud", category: "nature", keywords: ["cloud", "cloudy", "weather"] },
  "26C4": { codepoint: "26C4", name: "Snowman Without Snow", category: "nature", keywords: ["snowman", "winter", "cold"] },
  "26C5": { codepoint: "26C5", name: "Sun Behind Cloud", category: "nature", keywords: ["sun", "cloud", "partly cloudy"] },
  "2744": { codepoint: "2744", name: "Snowflake", category: "nature", keywords: ["snowflake", "winter", "cold", "snow"] },
  "1F300": { codepoint: "1F300", name: "Cyclone", category: "nature", keywords: ["cyclone", "hurricane", "weather"] },
  "1F301": { codepoint: "1F301", name: "Foggy", category: "nature", keywords: ["fog", "foggy", "weather"] },
  "1F302": { codepoint: "1F302", name: "Closed Umbrella", category: "objects", keywords: ["umbrella", "closed", "rain"] },
  "1F303": { codepoint: "1F303", name: "Night with Stars", category: "nature", keywords: ["night", "stars", "dark"] },
  "1F304": { codepoint: "1F304", name: "Sunrise Over Mountains", category: "nature", keywords: ["sunrise", "mountains", "morning"] },
  "1F305": { codepoint: "1F305", name: "Sunrise", category: "nature", keywords: ["sunrise", "morning", "dawn"] },
  "1F306": { codepoint: "1F306", name: "Cityscape at Dusk", category: "travel", keywords: ["city", "dusk", "evening"] },
  "1F307": { codepoint: "1F307", name: "Sunset", category: "nature", keywords: ["sunset", "evening", "dusk"] },
  "1F308": { codepoint: "1F308", name: "Rainbow", category: "nature", keywords: ["rainbow", "colorful", "weather"] },
  "1F309": { codepoint: "1F309", name: "Bridge at Night", category: "travel", keywords: ["bridge", "night", "lights"] },
  "1F30A": { codepoint: "1F30A", name: "Water Wave", category: "nature", keywords: ["wave", "water", "ocean"] },
  "1F30B": { codepoint: "1F30B", name: "Volcano", category: "nature", keywords: ["volcano", "eruption", "mountain"] },
  "1F30C": { codepoint: "1F30C", name: "Milky Way", category: "nature", keywords: ["milky way", "galaxy", "space"] },
  "1F30D": { codepoint: "1F30D", name: "Earth Globe Europe-Africa", category: "nature", keywords: ["earth", "globe", "europe", "africa"] },
  "1F30E": { codepoint: "1F30E", name: "Earth Globe Americas", category: "nature", keywords: ["earth", "globe", "americas"] },
  "1F30F": { codepoint: "1F30F", name: "Earth Globe Asia-Australia", category: "nature", keywords: ["earth", "globe", "asia", "australia"] },
  "1F310": { codepoint: "1F310", name: "Globe with Meridians", category: "symbols", keywords: ["globe", "meridians", "world"] },
  "1F311": { codepoint: "1F311", name: "New Moon", category: "nature", keywords: ["moon", "new", "dark"] },
  "1F312": { codepoint: "1F312", name: "Waxing Crescent Moon", category: "nature", keywords: ["moon", "waxing", "crescent"] },
  "1F313": { codepoint: "1F313", name: "First Quarter Moon", category: "nature", keywords: ["moon", "first quarter", "half"] },
  "1F314": { codepoint: "1F314", name: "Waxing Gibbous Moon", category: "nature", keywords: ["moon", "waxing", "gibbous"] },
  "1F315": { codepoint: "1F315", name: "Full Moon", category: "nature", keywords: ["moon", "full", "bright"] },
  "1F316": { codepoint: "1F316", name: "Waning Gibbous Moon", category: "nature", keywords: ["moon", "waning", "gibbous"] },
  "1F317": { codepoint: "1F317", name: "Last Quarter Moon", category: "nature", keywords: ["moon", "last quarter", "half"] },
  "1F318": { codepoint: "1F318", name: "Waning Crescent Moon", category: "nature", keywords: ["moon", "waning", "crescent"] },
  "1F319": { codepoint: "1F319", name: "Crescent Moon", category: "nature", keywords: ["moon", "crescent", "night"] },
  "1F31A": { codepoint: "1F31A", name: "New Moon Face", category: "nature", keywords: ["moon", "face", "new"] },
  "1F31B": { codepoint: "1F31B", name: "First Quarter Moon Face", category: "nature", keywords: ["moon", "face", "first quarter"] },
  "1F31C": { codepoint: "1F31C", name: "Last Quarter Moon Face", category: "nature", keywords: ["moon", "face", "last quarter"] },
  "1F31D": { codepoint: "1F31D", name: "Full Moon Face", category: "nature", keywords: ["moon", "face", "full"] },
  "1F31E": { codepoint: "1F31E", name: "Sun with Face", category: "nature", keywords: ["sun", "face", "sunny"] },
  "1F31F": { codepoint: "1F31F", name: "Glowing Star", category: "nature", keywords: ["star", "glowing", "bright"] },
  "1F320": { codepoint: "1F320", name: "Shooting Star", category: "nature", keywords: ["shooting star", "falling", "wish"] },

  // Symbols & Misc
  "2764": { codepoint: "2764", name: "Red Heart", category: "symbols", keywords: ["heart", "love", "red"] },
  "1F493": { codepoint: "1F493", name: "Beating Heart", category: "symbols", keywords: ["heart", "beating", "love"] },
  "1F494": { codepoint: "1F494", name: "Broken Heart", category: "symbols", keywords: ["heart", "broken", "sad"] },
  "1F495": { codepoint: "1F495", name: "Two Hearts", category: "symbols", keywords: ["hearts", "love", "two"] },
  "1F496": { codepoint: "1F496", name: "Sparkling Heart", category: "symbols", keywords: ["heart", "sparkling", "love"] },
  "1F497": { codepoint: "1F497", name: "Growing Heart", category: "symbols", keywords: ["heart", "growing", "love"] },
  "1F498": { codepoint: "1F498", name: "Heart with Arrow", category: "symbols", keywords: ["heart", "arrow", "cupid"] },
  "1F499": { codepoint: "1F499", name: "Blue Heart", category: "symbols", keywords: ["heart", "blue", "love"] },
  "1F49A": { codepoint: "1F49A", name: "Green Heart", category: "symbols", keywords: ["heart", "green", "love"] },
  "1F49B": { codepoint: "1F49B", name: "Yellow Heart", category: "symbols", keywords: ["heart", "yellow", "love"] },
  "1F49C": { codepoint: "1F49C", name: "Purple Heart", category: "symbols", keywords: ["heart", "purple", "love"] },
  "1F49D": { codepoint: "1F49D", name: "Heart with Ribbon", category: "symbols", keywords: ["heart", "ribbon", "gift"] },
  "1F49E": { codepoint: "1F49E", name: "Revolving Hearts", category: "symbols", keywords: ["hearts", "revolving", "love"] },
  "1F49F": { codepoint: "1F49F", name: "Heart Decoration", category: "symbols", keywords: ["heart", "decoration", "love"] },

  // Add more codepoints for default fallbacks
  "002D": { codepoint: "002D", name: "Hyphen-Minus", category: "symbols", keywords: ["hyphen", "minus", "dash"] },
  "1F004": { codepoint: "1F004", name: "Mahjong Red Dragon", category: "symbols", keywords: ["mahjong", "red", "dragon"] },
  "1F0CF": { codepoint: "1F0CF", name: "Playing Card Black Joker", category: "symbols", keywords: ["playing card", "joker", "black"] },
  "1F193": { codepoint: "1F193", name: "FREE Button", category: "symbols", keywords: ["free", "button", "text"] },
  "1F260": { codepoint: "1F260", name: "Rounded Symbol for Fu", category: "symbols", keywords: ["fu", "rounded", "symbol"] },
  "1F261": { codepoint: "1F261", name: "Rounded Symbol for Lu", category: "symbols", keywords: ["lu", "rounded", "symbol"] },
  "1F262": { codepoint: "1F262", name: "Rounded Symbol for Shou", category: "symbols", keywords: ["shou", "rounded", "symbol"] },
  "1F263": { codepoint: "1F263", name: "Rounded Symbol for Xi", category: "symbols", keywords: ["xi", "rounded", "symbol"] },
  "1F264": { codepoint: "1F264", name: "Rounded Symbol for Shuangxi", category: "symbols", keywords: ["shuangxi", "rounded", "symbol"] },
  "1F265": { codepoint: "1F265", name: "Rounded Symbol for Cai", category: "symbols", keywords: ["cai", "rounded", "symbol"] },
};

/**
 * Get emoji data by Unicode codepoint
 */
export function getEmojiData(codepoint: string): EmojiData | null {
  return emojiDatabase[codepoint.toUpperCase()] || null;
}

/**
 * Get all emojis by category
 */
export function getEmojisByCategory(category: string): EmojiData[] {
  return Object.values(emojiDatabase).filter(emoji => emoji.category === category);
}

/**
 * Get all available categories
 */
export function getAllEmojiCategories(): string[] {
  const categories = new Set(Object.values(emojiDatabase).map(emoji => emoji.category));
  return Array.from(categories).sort();
}

/**
 * Generate fallback emoji data for unknown codepoints
 */
export function generateFallbackEmojiData(filename: string): EmojiData {
  const codepoint = filename.replace('.svg', '').toUpperCase();
  
  // Handle multi-codepoint emojis (e.g., flag combinations)
  if (codepoint.includes('-')) {
    const parts = codepoint.split('-');
    if (parts.length === 2 && parts[0].startsWith('1F1') && parts[1].startsWith('1F1')) {
      return {
        codepoint,
        name: `Flag (${codepoint})`,
        category: "flags",
        keywords: ["flag", "country", "nation"]
      };
    }
    
    // Handle other multi-part sequences (skin tones, gender variants, etc.)
    return {
      codepoint,
      name: `Emoji Variant (${codepoint})`,
      category: "symbols",
      keywords: ["emoji", "variant", "unicode"]
    };
  }
  
  // Single codepoint fallback
  return {
    codepoint,
    name: `Unknown Emoji (${codepoint})`,
    category: "symbols",
    keywords: ["emoji", "unknown", "unicode"]
  };
}