/**
 * Auto-generated PNG emoji registry
 * Generated from 3757 PNG files on 2025-01-27T20:39:12.000Z
 * 
 * Categories: emotions, people, animals-nature, food-drink, activities, travel-places, objects, symbols, flags
 * DO NOT EDIT MANUALLY - Run 'node scripts/generatePngRegistry.js' to regenerate
 */

import { getCustomStamps, CustomStamp } from './customStamps';

export interface IconInfo {
  name: string;
  category: string;
  path: string;
  preview: string;
}

// Complete PNG emoji registry with all 3757 emojis
export const iconRegistry: IconInfo[] = [
  // Objects & Games
  { name: "Mahjong Red Dragon", category: "objects", path: "/png-emojis/1F004.png", preview: "🀄" },
  { name: "Playing Card Black Joker", category: "objects", path: "/png-emojis/1F0CF.png", preview: "🃏" },
  
  // Symbols
  { name: "FREE Button", category: "symbols", path: "/png-emojis/1F193.png", preview: "🆓" },
  
  // Flags - All Country Flags
  { name: "Ascension Island Flag", category: "flags", path: "/png-emojis/1F1E6-1F1E8.png", preview: "🇦🇨" },
  { name: "Andorra Flag", category: "flags", path: "/png-emojis/1F1E6-1F1E9.png", preview: "🇦🇩" },
  { name: "United Arab Emirates Flag", category: "flags", path: "/png-emojis/1F1E6-1F1EA.png", preview: "🇦🇪" },
  { name: "Afghanistan Flag", category: "flags", path: "/png-emojis/1F1E6-1F1EB.png", preview: "🇦🇫" },
  { name: "Antigua & Barbuda Flag", category: "flags", path: "/png-emojis/1F1E6-1F1EC.png", preview: "🇦🇬" },
  { name: "Anguilla Flag", category: "flags", path: "/png-emojis/1F1E6-1F1EE.png", preview: "🇦🇮" },
  { name: "Albania Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F1.png", preview: "🇦🇱" },
  { name: "Armenia Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F2.png", preview: "🇦🇲" },
  { name: "Angola Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F4.png", preview: "🇦🇴" },
  { name: "Antarctica Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F6.png", preview: "🇦🇶" },
  { name: "Argentina Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F7.png", preview: "🇦🇷" },
  { name: "American Samoa Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F8.png", preview: "🇦🇸" },
  { name: "Austria Flag", category: "flags", path: "/png-emojis/1F1E6-1F1F9.png", preview: "🇦🇹" },
  { name: "Australia Flag", category: "flags", path: "/png-emojis/1F1E6-1F1FA.png", preview: "🇦🇺" },
  { name: "Aruba Flag", category: "flags", path: "/png-emojis/1F1E6-1F1FC.png", preview: "🇦🇼" },
  { name: "Åland Islands Flag", category: "flags", path: "/png-emojis/1F1E6-1F1FD.png", preview: "🇦🇽" },
  { name: "Azerbaijan Flag", category: "flags", path: "/png-emojis/1F1E6-1F1FF.png", preview: "🇦🇿" },
  { name: "Bosnia & Herzegovina Flag", category: "flags", path: "/png-emojis/1F1E7-1F1E6.png", preview: "🇧🇦" },
  { name: "Barbados Flag", category: "flags", path: "/png-emojis/1F1E7-1F1E7.png", preview: "🇧🇧" },
  { name: "Bangladesh Flag", category: "flags", path: "/png-emojis/1F1E7-1F1E9.png", preview: "🇧🇩" },
  { name: "Belgium Flag", category: "flags", path: "/png-emojis/1F1E7-1F1EA.png", preview: "🇧🇪" },
  { name: "Burkina Faso Flag", category: "flags", path: "/png-emojis/1F1E7-1F1EB.png", preview: "🇧🇫" },
  { name: "Bulgaria Flag", category: "flags", path: "/png-emojis/1F1E7-1F1EC.png", preview: "🇧🇬" },
  { name: "Bahrain Flag", category: "flags", path: "/png-emojis/1F1E7-1F1ED.png", preview: "🇧🇭" },
  { name: "Burundi Flag", category: "flags", path: "/png-emojis/1F1E7-1F1EE.png", preview: "🇧🇮" },
  { name: "Benin Flag", category: "flags", path: "/png-emojis/1F1E7-1F1EF.png", preview: "🇧🇯" },
  { name: "St. Barthélemy Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F1.png", preview: "🇧🇱" },
  { name: "Bermuda Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F2.png", preview: "🇧🇲" },
  { name: "Brunei Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F3.png", preview: "🇧🇳" },
  { name: "Bolivia Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F4.png", preview: "🇧🇴" },
  { name: "Caribbean Netherlands Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F6.png", preview: "🇧🇶" },
  { name: "Brazil Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F7.png", preview: "🇧🇷" },
  { name: "Bahamas Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F8.png", preview: "🇧🇸" },
  { name: "Bhutan Flag", category: "flags", path: "/png-emojis/1F1E7-1F1F9.png", preview: "🇧🇹" },
  { name: "Bouvet Island Flag", category: "flags", path: "/png-emojis/1F1E7-1F1FB.png", preview: "🇧🇻" },
  { name: "Botswana Flag", category: "flags", path: "/png-emojis/1F1E7-1F1FC.png", preview: "🇧🇼" },
  { name: "Belarus Flag", category: "flags", path: "/png-emojis/1F1E7-1F1FE.png", preview: "🇧🇾" },
  { name: "Belize Flag", category: "flags", path: "/png-emojis/1F1E7-1F1FF.png", preview: "🇧🇿" },
  { name: "Canada Flag", category: "flags", path: "/png-emojis/1F1E8-1F1E6.png", preview: "🇨🇦" },
  { name: "Cocos (Keeling) Islands Flag", category: "flags", path: "/png-emojis/1F1E8-1F1E8.png", preview: "🇨🇨" },
  { name: "Congo - Kinshasa Flag", category: "flags", path: "/png-emojis/1F1E8-1F1E9.png", preview: "🇨🇩" },
  { name: "Central African Republic Flag", category: "flags", path: "/png-emojis/1F1E8-1F1EB.png", preview: "🇨🇫" },
  { name: "Congo - Brazzaville Flag", category: "flags", path: "/png-emojis/1F1E8-1F1EC.png", preview: "🇨🇬" },
  { name: "Switzerland Flag", category: "flags", path: "/png-emojis/1F1E8-1F1ED.png", preview: "🇨🇭" },
  { name: "Côte d'Ivoire Flag", category: "flags", path: "/png-emojis/1F1E8-1F1EE.png", preview: "🇨🇮" },
  { name: "Cook Islands Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F0.png", preview: "🇨🇰" },
  { name: "Chile Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F1.png", preview: "🇨🇱" },
  { name: "Cameroon Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F2.png", preview: "🇨🇲" },
  { name: "China Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F3.png", preview: "🇨🇳" },
  { name: "Colombia Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F4.png", preview: "🇨🇴" },
  { name: "Clipperton Island Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F5.png", preview: "🇨🇵" },
  { name: "Costa Rica Flag", category: "flags", path: "/png-emojis/1F1E8-1F1F7.png", preview: "🇨🇷" },
  { name: "Cuba Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FA.png", preview: "🇨🇺" },
  { name: "Cape Verde Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FB.png", preview: "🇨🇻" },
  { name: "Curaçao Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FC.png", preview: "🇨🇼" },
  { name: "Christmas Island Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FD.png", preview: "🇨🇽" },
  { name: "Cyprus Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FE.png", preview: "🇨🇾" },
  { name: "Czechia Flag", category: "flags", path: "/png-emojis/1F1E8-1F1FF.png", preview: "🇨🇿" },
  { name: "Germany Flag", category: "flags", path: "/png-emojis/1F1E9-1F1EA.png", preview: "🇩🇪" },
  { name: "Diego Garcia Flag", category: "flags", path: "/png-emojis/1F1E9-1F1EC.png", preview: "🇩🇬" },
  { name: "Djibouti Flag", category: "flags", path: "/png-emojis/1F1E9-1F1EF.png", preview: "🇩🇯" },
  { name: "Denmark Flag", category: "flags", path: "/png-emojis/1F1E9-1F1F0.png", preview: "🇩🇰" },
  { name: "Dominica Flag", category: "flags", path: "/png-emojis/1F1E9-1F1F2.png", preview: "🇩🇲" },
  { name: "Dominican Republic Flag", category: "flags", path: "/png-emojis/1F1E9-1F1F4.png", preview: "🇩🇴" },
  { name: "Algeria Flag", category: "flags", path: "/png-emojis/1F1E9-1F1FF.png", preview: "🇩🇿" },
  { name: "Ceuta & Melilla Flag", category: "flags", path: "/png-emojis/1F1EA-1F1E6.png", preview: "🇪🇦" },
  { name: "Ecuador Flag", category: "flags", path: "/png-emojis/1F1EA-1F1E8.png", preview: "🇪🇨" },
  { name: "Estonia Flag", category: "flags", path: "/png-emojis/1F1EA-1F1EA.png", preview: "🇪🇪" },
  { name: "Egypt Flag", category: "flags", path: "/png-emojis/1F1EA-1F1EC.png", preview: "🇪🇬" },
  { name: "Western Sahara Flag", category: "flags", path: "/png-emojis/1F1EA-1F1ED.png", preview: "🇪🇭" },
  { name: "Eritrea Flag", category: "flags", path: "/png-emojis/1F1EA-1F1F7.png", preview: "🇪🇷" },
  { name: "Spain Flag", category: "flags", path: "/png-emojis/1F1EA-1F1F8.png", preview: "🇪🇸" },
  { name: "Ethiopia Flag", category: "flags", path: "/png-emojis/1F1EA-1F1F9.png", preview: "🇪🇹" },
  { name: "European Union Flag", category: "flags", path: "/png-emojis/1F1EA-1F1FA.png", preview: "🇪🇺" },
  { name: "Finland Flag", category: "flags", path: "/png-emojis/1F1EB-1F1EE.png", preview: "🇫🇮" },
  { name: "Fiji Flag", category: "flags", path: "/png-emojis/1F1EB-1F1EF.png", preview: "🇫🇯" },
  { name: "Falkland Islands Flag", category: "flags", path: "/png-emojis/1F1EB-1F1F0.png", preview: "🇫🇰" },
  { name: "Micronesia Flag", category: "flags", path: "/png-emojis/1F1EB-1F1F2.png", preview: "🇫🇲" },
  { name: "Faroe Islands Flag", category: "flags", path: "/png-emojis/1F1EB-1F1F4.png", preview: "🇫🇴" },
  { name: "France Flag", category: "flags", path: "/png-emojis/1F1EB-1F1F7.png", preview: "🇫🇷" },
  { name: "Gabon Flag", category: "flags", path: "/png-emojis/1F1EC-1F1E6.png", preview: "🇬🇦" },
  { name: "United Kingdom Flag", category: "flags", path: "/png-emojis/1F1EC-1F1E7.png", preview: "🇬🇧" },
  { name: "Grenada Flag", category: "flags", path: "/png-emojis/1F1EC-1F1E9.png", preview: "🇬🇩" },
  { name: "Georgia Flag", category: "flags", path: "/png-emojis/1F1EC-1F1EA.png", preview: "🇬🇪" },
  { name: "French Guiana Flag", category: "flags", path: "/png-emojis/1F1EC-1F1EB.png", preview: "🇬🇫" },
  { name: "Guernsey Flag", category: "flags", path: "/png-emojis/1F1EC-1F1EC.png", preview: "🇬🇬" },
  { name: "Ghana Flag", category: "flags", path: "/png-emojis/1F1EC-1F1ED.png", preview: "🇬🇭" },
  { name: "Gibraltar Flag", category: "flags", path: "/png-emojis/1F1EC-1F1EE.png", preview: "🇬🇮" },
  { name: "Greenland Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F1.png", preview: "🇬🇱" },
  { name: "Gambia Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F2.png", preview: "🇬🇲" },
  { name: "Guinea Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F3.png", preview: "🇬🇳" },
  { name: "Guadeloupe Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F5.png", preview: "🇬🇵" },
  { name: "Equatorial Guinea Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F6.png", preview: "🇬🇶" },
  { name: "Greece Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F7.png", preview: "🇬🇷" },
  { name: "South Georgia & South Sandwich Islands Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F8.png", preview: "🇬🇸" },
  { name: "Guatemala Flag", category: "flags", path: "/png-emojis/1F1EC-1F1F9.png", preview: "🇬🇹" },
  { name: "Guam Flag", category: "flags", path: "/png-emojis/1F1EC-1F1FA.png", preview: "🇬🇺" },
  { name: "Guinea-Bissau Flag", category: "flags", path: "/png-emojis/1F1EC-1F1FC.png", preview: "🇬🇼" },
  { name: "Guyana Flag", category: "flags", path: "/png-emojis/1F1EC-1F1FE.png", preview: "🇬🇾" },
  { name: "Hong Kong SAR China Flag", category: "flags", path: "/png-emojis/1F1ED-1F1F0.png", preview: "🇭🇰" },
  { name: "Heard & McDonald Islands Flag", category: "flags", path: "/png-emojis/1F1ED-1F1F2.png", preview: "🇭🇲" },
  { name: "Honduras Flag", category: "flags", path: "/png-emojis/1F1ED-1F1F3.png", preview: "🇭🇳" },
  { name: "Croatia Flag", category: "flags", path: "/png-emojis/1F1ED-1F1F7.png", preview: "🇭🇷" },
  { name: "Haiti Flag", category: "flags", path: "/png-emojis/1F1ED-1F1F9.png", preview: "🇭🇹" },
  { name: "Hungary Flag", category: "flags", path: "/png-emojis/1F1ED-1F1FA.png", preview: "🇭🇺" },
  { name: "Canary Islands Flag", category: "flags", path: "/png-emojis/1F1EE-1F1E8.png", preview: "🇮🇨" },
  { name: "Indonesia Flag", category: "flags", path: "/png-emojis/1F1EE-1F1E9.png", preview: "🇮🇩" },
  { name: "Ireland Flag", category: "flags", path: "/png-emojis/1F1EE-1F1EA.png", preview: "🇮🇪" },
  { name: "Israel Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F1.png", preview: "🇮🇱" },
  { name: "Isle of Man Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F2.png", preview: "🇮🇲" },
  { name: "India Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F3.png", preview: "🇮🇳" },
  { name: "British Indian Ocean Territory Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F4.png", preview: "🇮🇴" },
  { name: "Iraq Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F6.png", preview: "🇮🇶" },
  { name: "Iran Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F7.png", preview: "🇮🇷" },
  { name: "Iceland Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F8.png", preview: "🇮🇸" },
  { name: "Italy Flag", category: "flags", path: "/png-emojis/1F1EE-1F1F9.png", preview: "🇮🇹" },
  { name: "Jersey Flag", category: "flags", path: "/png-emojis/1F1EF-1F1EA.png", preview: "🇯🇪" },
  { name: "Jamaica Flag", category: "flags", path: "/png-emojis/1F1EF-1F1F2.png", preview: "🇯🇲" },
  { name: "Jordan Flag", category: "flags", path: "/png-emojis/1F1EF-1F1F4.png", preview: "🇯🇴" },
  { name: "Japan Flag", category: "flags", path: "/png-emojis/1F1EF-1F1F5.png", preview: "🇯🇵" },
  { name: "Kenya Flag", category: "flags", path: "/png-emojis/1F1F0-1F1EA.png", preview: "🇰🇪" },
  { name: "Kyrgyzstan Flag", category: "flags", path: "/png-emojis/1F1F0-1F1EC.png", preview: "🇰🇬" },
  { name: "Cambodia Flag", category: "flags", path: "/png-emojis/1F1F0-1F1ED.png", preview: "🇰🇭" },
  { name: "Kiribati Flag", category: "flags", path: "/png-emojis/1F1F0-1F1EE.png", preview: "🇰🇮" },
  { name: "Comoros Flag", category: "flags", path: "/png-emojis/1F1F0-1F1F2.png", preview: "🇰🇲" },
  { name: "St. Kitts & Nevis Flag", category: "flags", path: "/png-emojis/1F1F0-1F1F3.png", preview: "🇰🇳" },
  { name: "North Korea Flag", category: "flags", path: "/png-emojis/1F1F0-1F1F5.png", preview: "🇰🇵" },
  { name: "South Korea Flag", category: "flags", path: "/png-emojis/1F1F0-1F1F7.png", preview: "🇰🇷" },
  { name: "Kuwait Flag", category: "flags", path: "/png-emojis/1F1F0-1F1FC.png", preview: "🇰🇼" },
  { name: "Cayman Islands Flag", category: "flags", path: "/png-emojis/1F1F0-1F1FE.png", preview: "🇰🇾" },
  { name: "Kazakhstan Flag", category: "flags", path: "/png-emojis/1F1F0-1F1FF.png", preview: "🇰🇿" },
  { name: "Laos Flag", category: "flags", path: "/png-emojis/1F1F1-1F1E6.png", preview: "🇱🇦" },
  { name: "Lebanon Flag", category: "flags", path: "/png-emojis/1F1F1-1F1E7.png", preview: "🇱🇧" },
  { name: "St. Lucia Flag", category: "flags", path: "/png-emojis/1F1F1-1F1E8.png", preview: "🇱🇨" },
  { name: "Liechtenstein Flag", category: "flags", path: "/png-emojis/1F1F1-1F1EE.png", preview: "🇱🇮" },
  { name: "Sri Lanka Flag", category: "flags", path: "/png-emojis/1F1F1-1F1F0.png", preview: "🇱🇰" },
  { name: "Liberia Flag", category: "flags", path: "/png-emojis/1F1F1-1F1F7.png", preview: "🇱🇷" },
  { name: "Lesotho Flag", category: "flags", path: "/png-emojis/1F1F1-1F1F8.png", preview: "🇱🇸" },
  { name: "Lithuania Flag", category: "flags", path: "/png-emojis/1F1F1-1F1F9.png", preview: "🇱🇹" },
  { name: "Luxembourg Flag", category: "flags", path: "/png-emojis/1F1F1-1F1FA.png", preview: "🇱🇺" },
  { name: "Latvia Flag", category: "flags", path: "/png-emojis/1F1F1-1F1FB.png", preview: "🇱🇻" },
  { name: "Libya Flag", category: "flags", path: "/png-emojis/1F1F1-1F1FE.png", preview: "🇱🇾" },
  { name: "Morocco Flag", category: "flags", path: "/png-emojis/1F1F2-1F1E6.png", preview: "🇲🇦" },
  { name: "Monaco Flag", category: "flags", path: "/png-emojis/1F1F2-1F1E8.png", preview: "🇲🇨" },
  { name: "Moldova Flag", category: "flags", path: "/png-emojis/1F1F2-1F1E9.png", preview: "🇲🇩" },
  { name: "Montenegro Flag", category: "flags", path: "/png-emojis/1F1F2-1F1EA.png", preview: "🇲🇪" },
  { name: "St. Martin Flag", category: "flags", path: "/png-emojis/1F1F2-1F1EB.png", preview: "🇲🇫" },
  { name: "Madagascar Flag", category: "flags", path: "/png-emojis/1F1F2-1F1EC.png", preview: "🇲🇬" },
  { name: "Marshall Islands Flag", category: "flags", path: "/png-emojis/1F1F2-1F1ED.png", preview: "🇲🇭" },
  { name: "North Macedonia Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F0.png", preview: "🇲🇰" },
  { name: "Mali Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F1.png", preview: "🇲🇱" },
  { name: "Myanmar (Burma) Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F2.png", preview: "🇲🇲" },
  { name: "Mongolia Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F3.png", preview: "🇲🇳" },
  { name: "Macao SAR China Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F4.png", preview: "🇲🇴" },
  { name: "Northern Mariana Islands Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F5.png", preview: "🇲🇵" },
  { name: "Martinique Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F6.png", preview: "🇲🇶" },
  { name: "Mauritania Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F7.png", preview: "🇲🇷" },
  { name: "Montserrat Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F8.png", preview: "🇲🇸" },
  { name: "Malta Flag", category: "flags", path: "/png-emojis/1F1F2-1F1F9.png", preview: "🇲🇹" },
  { name: "Mauritius Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FA.png", preview: "🇲🇺" },
  { name: "Maldives Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FB.png", preview: "🇲🇻" },
  { name: "Malawi Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FC.png", preview: "🇲🇼" },
  { name: "Mexico Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FD.png", preview: "🇲🇽" },
  { name: "Malaysia Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FE.png", preview: "🇲🇾" },
  { name: "Mozambique Flag", category: "flags", path: "/png-emojis/1F1F2-1F1FF.png", preview: "🇲🇿" },
  { name: "Namibia Flag", category: "flags", path: "/png-emojis/1F1F3-1F1E6.png", preview: "🇳🇦" },
  { name: "New Caledonia Flag", category: "flags", path: "/png-emojis/1F1F3-1F1E8.png", preview: "🇳🇨" },
  { name: "Niger Flag", category: "flags", path: "/png-emojis/1F1F3-1F1EA.png", preview: "🇳🇪" },
  { name: "Norfolk Island Flag", category: "flags", path: "/png-emojis/1F1F3-1F1EB.png", preview: "🇳🇫" },
  { name: "Nigeria Flag", category: "flags", path: "/png-emojis/1F1F3-1F1EC.png", preview: "🇳🇬" },
  { name: "Nicaragua Flag", category: "flags", path: "/png-emojis/1F1F3-1F1EE.png", preview: "🇳🇮" },
  { name: "Netherlands Flag", category: "flags", path: "/png-emojis/1F1F3-1F1F1.png", preview: "🇳🇱" },
  { name: "Norway Flag", category: "flags", path: "/png-emojis/1F1F3-1F1F4.png", preview: "🇳🇴" },
  { name: "Nepal Flag", category: "flags", path: "/png-emojis/1F1F3-1F1F5.png", preview: "🇳🇵" },
  { name: "Nauru Flag", category: "flags", path: "/png-emojis/1F1F3-1F1F7.png", preview: "🇳🇷" },
  { name: "Niue Flag", category: "flags", path: "/png-emojis/1F1F3-1F1FA.png", preview: "🇳🇺" },
  { name: "New Zealand Flag", category: "flags", path: "/png-emojis/1F1F3-1F1FF.png", preview: "🇳🇿" },
  { name: "Oman Flag", category: "flags", path: "/png-emojis/1F1F4-1F1F2.png", preview: "🇴🇲" },
  { name: "Panama Flag", category: "flags", path: "/png-emojis/1F1F5-1F1E6.png", preview: "🇵🇦" },
  { name: "Peru Flag", category: "flags", path: "/png-emojis/1F1F5-1F1EA.png", preview: "🇵🇪" },
  { name: "French Polynesia Flag", category: "flags", path: "/png-emojis/1F1F5-1F1EB.png", preview: "🇵🇫" },
  { name: "Papua New Guinea Flag", category: "flags", path: "/png-emojis/1F1F5-1F1EC.png", preview: "🇵🇬" },
  { name: "Philippines Flag", category: "flags", path: "/png-emojis/1F1F5-1F1ED.png", preview: "🇵🇭" },
  { name: "Pakistan Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F0.png", preview: "🇵🇰" },
  { name: "Poland Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F1.png", preview: "🇵🇱" },
  { name: "St. Pierre & Miquelon Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F2.png", preview: "🇵🇲" },
  { name: "Pitcairn Islands Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F3.png", preview: "🇵🇳" },
  { name: "Puerto Rico Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F7.png", preview: "🇵🇷" },
  { name: "Palestinian Territories Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F8.png", preview: "🇵🇸" },
  { name: "Portugal Flag", category: "flags", path: "/png-emojis/1F1F5-1F1F9.png", preview: "🇵🇹" },
  { name: "Palau Flag", category: "flags", path: "/png-emojis/1F1F5-1F1FC.png", preview: "🇵🇼" },
  { name: "Paraguay Flag", category: "flags", path: "/png-emojis/1F1F5-1F1FE.png", preview: "🇵🇾" },
  { name: "Qatar Flag", category: "flags", path: "/png-emojis/1F1F6-1F1E6.png", preview: "🇶🇦" },
  { name: "Réunion Flag", category: "flags", path: "/png-emojis/1F1F7-1F1EA.png", preview: "🇷🇪" },
  { name: "Romania Flag", category: "flags", path: "/png-emojis/1F1F7-1F1F4.png", preview: "🇷🇴" },
  { name: "Serbia Flag", category: "flags", path: "/png-emojis/1F1F7-1F1F8.png", preview: "🇷🇸" },
  { name: "Russia Flag", category: "flags", path: "/png-emojis/1F1F7-1F1FA.png", preview: "🇷🇺" },
  { name: "Rwanda Flag", category: "flags", path: "/png-emojis/1F1F7-1F1FC.png", preview: "🇷🇼" },
  { name: "Saudi Arabia Flag", category: "flags", path: "/png-emojis/1F1F8-1F1E6.png", preview: "🇸🇦" },
  { name: "Solomon Islands Flag", category: "flags", path: "/png-emojis/1F1F8-1F1E7.png", preview: "🇸🇧" },
  { name: "Seychelles Flag", category: "flags", path: "/png-emojis/1F1F8-1F1E8.png", preview: "🇸🇨" },
  { name: "Sudan Flag", category: "flags", path: "/png-emojis/1F1F8-1F1E9.png", preview: "🇸🇩" },
  { name: "Sweden Flag", category: "flags", path: "/png-emojis/1F1F8-1F1EA.png", preview: "🇸🇪" },
  { name: "Singapore Flag", category: "flags", path: "/png-emojis/1F1F8-1F1EC.png", preview: "🇸🇬" },
  { name: "St. Helena Flag", category: "flags", path: "/png-emojis/1F1F8-1F1ED.png", preview: "🇸🇭" },
  { name: "Slovenia Flag", category: "flags", path: "/png-emojis/1F1F8-1F1EE.png", preview: "🇸🇮" },
  { name: "Svalbard & Jan Mayen Flag", category: "flags", path: "/png-emojis/1F1F8-1F1EF.png", preview: "🇸🇯" },
  { name: "Slovakia Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F0.png", preview: "🇸🇰" },
  { name: "Sierra Leone Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F1.png", preview: "🇸🇱" },
  { name: "San Marino Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F2.png", preview: "🇸🇲" },
  { name: "Senegal Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F3.png", preview: "🇸🇳" },
  { name: "Somalia Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F4.png", preview: "🇸🇴" },
  { name: "Suriname Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F7.png", preview: "🇸🇷" },
  { name: "South Sudan Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F8.png", preview: "🇸🇸" },
  { name: "São Tomé & Príncipe Flag", category: "flags", path: "/png-emojis/1F1F8-1F1F9.png", preview: "🇸🇹" },
  { name: "El Salvador Flag", category: "flags", path: "/png-emojis/1F1F8-1F1FB.png", preview: "🇸🇻" },
  { name: "Sint Maarten Flag", category: "flags", path: "/png-emojis/1F1F8-1F1FD.png", preview: "🇸🇽" },
  { name: "Syria Flag", category: "flags", path: "/png-emojis/1F1F8-1F1FE.png", preview: "🇸🇾" },
  { name: "Eswatini Flag", category: "flags", path: "/png-emojis/1F1F8-1F1FF.png", preview: "🇸🇿" },
  { name: "Tristan da Cunha Flag", category: "flags", path: "/png-emojis/1F1F9-1F1E6.png", preview: "🇹🇦" },
  { name: "Turks & Caicos Islands Flag", category: "flags", path: "/png-emojis/1F1F9-1F1E8.png", preview: "🇹🇨" },
  { name: "Chad Flag", category: "flags", path: "/png-emojis/1F1F9-1F1E9.png", preview: "🇹🇩" },
  { name: "French Southern Territories Flag", category: "flags", path: "/png-emojis/1F1F9-1F1EB.png", preview: "🇹🇫" },
  { name: "Togo Flag", category: "flags", path: "/png-emojis/1F1F9-1F1EC.png", preview: "🇹🇬" },
  { name: "Thailand Flag", category: "flags", path: "/png-emojis/1F1F9-1F1ED.png", preview: "🇹🇭" },
  { name: "Tajikistan Flag", category: "flags", path: "/png-emojis/1F1F9-1F1EF.png", preview: "🇹🇯" },
  { name: "Tokelau Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F0.png", preview: "🇹🇰" },
  { name: "Timor-Leste Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F1.png", preview: "🇹🇱" },
  { name: "Turkmenistan Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F2.png", preview: "🇹🇲" },
  { name: "Tunisia Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F3.png", preview: "🇹🇳" },
  { name: "Tonga Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F4.png", preview: "🇹🇴" },
  { name: "Turkey Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F7.png", preview: "🇹🇷" },
  { name: "Trinidad & Tobago Flag", category: "flags", path: "/png-emojis/1F1F9-1F1F9.png", preview: "🇹🇹" },
  { name: "Tuvalu Flag", category: "flags", path: "/png-emojis/1F1F9-1F1FB.png", preview: "🇹🇻" },
  { name: "Taiwan Flag", category: "flags", path: "/png-emojis/1F1F9-1F1FC.png", preview: "🇹🇼" },
  { name: "Tanzania Flag", category: "flags", path: "/png-emojis/1F1F9-1F1FF.png", preview: "🇹🇿" },
  { name: "Ukraine Flag", category: "flags", path: "/png-emojis/1F1FA-1F1E6.png", preview: "🇺🇦" },
  { name: "Uganda Flag", category: "flags", path: "/png-emojis/1F1FA-1F1EC.png", preview: "🇺🇬" },
  { name: "U.S. Outlying Islands Flag", category: "flags", path: "/png-emojis/1F1FA-1F1F2.png", preview: "🇺🇲" },
  { name: "United Nations Flag", category: "flags", path: "/png-emojis/1F1FA-1F1F3.png", preview: "🇺🇳" },
  { name: "United States Flag", category: "flags", path: "/png-emojis/1F1FA-1F1F8.png", preview: "🇺🇸" },
  { name: "Uruguay Flag", category: "flags", path: "/png-emojis/1F1FA-1F1FE.png", preview: "🇺🇾" },
  { name: "Uzbekistan Flag", category: "flags", path: "/png-emojis/1F1FA-1F1FF.png", preview: "🇺🇿" },
  { name: "Vatican City Flag", category: "flags", path: "/png-emojis/1F1FB-1F1E6.png", preview: "🇻🇦" },
  { name: "St. Vincent & Grenadines Flag", category: "flags", path: "/png-emojis/1F1FB-1F1E8.png", preview: "🇻🇨" },
  { name: "Venezuela Flag", category: "flags", path: "/png-emojis/1F1FB-1F1EA.png", preview: "🇻🇪" },
  { name: "British Virgin Islands Flag", category: "flags", path: "/png-emojis/1F1FB-1F1EC.png", preview: "🇻🇬" },
  { name: "U.S. Virgin Islands Flag", category: "flags", path: "/png-emojis/1F1FB-1F1EE.png", preview: "🇻🇮" },
  { name: "Vietnam Flag", category: "flags", path: "/png-emojis/1F1FB-1F1F3.png", preview: "🇻🇳" },
  { name: "Vanuatu Flag", category: "flags", path: "/png-emojis/1F1FB-1F1FA.png", preview: "🇻🇺" },
  { name: "Wallis & Futuna Flag", category: "flags", path: "/png-emojis/1F1FC-1F1EB.png", preview: "🇼🇫" },
  { name: "Samoa Flag", category: "flags", path: "/png-emojis/1F1FC-1F1F8.png", preview: "🇼🇸" },
  { name: "Kosovo Flag", category: "flags", path: "/png-emojis/1F1FD-1F1F0.png", preview: "🇽🇰" },
  { name: "Yemen Flag", category: "flags", path: "/png-emojis/1F1FE-1F1EA.png", preview: "🇾🇪" },
  { name: "Mayotte Flag", category: "flags", path: "/png-emojis/1F1FE-1F1F9.png", preview: "🇾🇹" },
  { name: "South Africa Flag", category: "flags", path: "/png-emojis/1F1FF-1F1E6.png", preview: "🇿🇦" },
  { name: "Zambia Flag", category: "flags", path: "/png-emojis/1F1FF-1F1F2.png", preview: "🇿🇲" },
  { name: "Zimbabwe Flag", category: "flags", path: "/png-emojis/1F1FF-1F1FC.png", preview: "🇿🇼" },

  // Nature & Weather - All entries
  { name: "Cyclone", category: "animals-nature", path: "/png-emojis/1F300.png", preview: "🌀" },
  { name: "Foggy", category: "animals-nature", path: "/png-emojis/1F301.png", preview: "🌁" },
  { name: "Closed Umbrella", category: "animals-nature", path: "/png-emojis/1F302.png", preview: "🌂" },
  { name: "Night with Stars", category: "animals-nature", path: "/png-emojis/1F303.png", preview: "🌃" },
  { name: "Sunrise Over Mountains", category: "animals-nature", path: "/png-emojis/1F304.png", preview: "🌄" },
  { name: "Sunrise", category: "animals-nature", path: "/png-emojis/1F305.png", preview: "🌅" },
  { name: "Cityscape at Dusk", category: "animals-nature", path: "/png-emojis/1F306.png", preview: "🌆" },
  { name: "Sunset", category: "animals-nature", path: "/png-emojis/1F307.png", preview: "🌇" },
  { name: "Rainbow", category: "animals-nature", path: "/png-emojis/1F308.png", preview: "🌈" },
  { name: "Bridge at Night", category: "animals-nature", path: "/png-emojis/1F309.png", preview: "🌉" },
  { name: "Water Wave", category: "animals-nature", path: "/png-emojis/1F30A.png", preview: "🌊" },
  { name: "Volcano", category: "animals-nature", path: "/png-emojis/1F30B.png", preview: "🌋" },
  { name: "Milky Way", category: "animals-nature", path: "/png-emojis/1F30C.png", preview: "🌌" },
  { name: "Globe Showing Europe-Africa", category: "animals-nature", path: "/png-emojis/1F30D.png", preview: "🌍" },
  { name: "Globe Showing Americas", category: "animals-nature", path: "/png-emojis/1F30E.png", preview: "🌎" },
  { name: "Globe Showing Asia-Australia", category: "animals-nature", path: "/png-emojis/1F30F.png", preview: "🌏" },
  { name: "Globe with Meridians", category: "animals-nature", path: "/png-emojis/1F310.png", preview: "🌐" },
  { name: "New Moon", category: "animals-nature", path: "/png-emojis/1F311.png", preview: "🌑" },
  { name: "Waxing Crescent Moon", category: "animals-nature", path: "/png-emojis/1F312.png", preview: "🌒" },
  { name: "First Quarter Moon", category: "animals-nature", path: "/png-emojis/1F313.png", preview: "🌓" },
  { name: "Waxing Gibbous Moon", category: "animals-nature", path: "/png-emojis/1F314.png", preview: "🌔" },
  { name: "Full Moon", category: "animals-nature", path: "/png-emojis/1F315.png", preview: "🌕" },
  { name: "Waning Gibbous Moon", category: "animals-nature", path: "/png-emojis/1F316.png", preview: "🌖" },
  { name: "Last Quarter Moon", category: "animals-nature", path: "/png-emojis/1F317.png", preview: "🌗" },
  { name: "Waning Crescent Moon", category: "animals-nature", path: "/png-emojis/1F318.png", preview: "🌘" },
  { name: "Crescent Moon", category: "animals-nature", path: "/png-emojis/1F319.png", preview: "🌙" },
  { name: "New Moon Face", category: "animals-nature", path: "/png-emojis/1F31A.png", preview: "🌚" },
  { name: "First Quarter Moon Face", category: "animals-nature", path: "/png-emojis/1F31B.png", preview: "🌛" },
  { name: "Last Quarter Moon Face", category: "animals-nature", path: "/png-emojis/1F31C.png", preview: "🌜" },
  { name: "Full Moon Face", category: "animals-nature", path: "/png-emojis/1F31D.png", preview: "🌝" },
  { name: "Sun with Face", category: "animals-nature", path: "/png-emojis/1F31E.png", preview: "🌞" },
  { name: "Glowing Star", category: "animals-nature", path: "/png-emojis/1F31F.png", preview: "🌟" },
  { name: "Shooting Star", category: "animals-nature", path: "/png-emojis/1F320.png", preview: "🌠" },
  { name: "Thermometer", category: "animals-nature", path: "/png-emojis/1F321.png", preview: "🌡️" },
  { name: "Sun Behind Small Cloud", category: "animals-nature", path: "/png-emojis/1F324.png", preview: "🌤️" },
  { name: "Sun Behind Large Cloud", category: "animals-nature", path: "/png-emojis/1F325.png", preview: "🌥️" },
  { name: "Sun Behind Rain Cloud", category: "animals-nature", path: "/png-emojis/1F326.png", preview: "🌦️" },
  { name: "Cloud with Rain", category: "animals-nature", path: "/png-emojis/1F327.png", preview: "🌧️" },
  { name: "Cloud with Snow", category: "animals-nature", path: "/png-emojis/1F328.png", preview: "🌨️" },
  { name: "Cloud with Lightning", category: "animals-nature", path: "/png-emojis/1F329.png", preview: "🌩️" },
  { name: "Tornado", category: "animals-nature", path: "/png-emojis/1F32A.png", preview: "🌪️" },
  { name: "Fog", category: "animals-nature", path: "/png-emojis/1F32B.png", preview: "🌫️" },
  { name: "Wind Face", category: "animals-nature", path: "/png-emojis/1F32C.png", preview: "🌬️" },

  // Food & Drink - Complete set
  { name: "Hot Dog", category: "food-drink", path: "/png-emojis/1F32D.png", preview: "🌭" },
  { name: "Taco", category: "food-drink", path: "/png-emojis/1F32E.png", preview: "🌮" },
  { name: "Burrito", category: "food-drink", path: "/png-emojis/1F32F.png", preview: "🌯" },
  { name: "Chestnut", category: "food-drink", path: "/png-emojis/1F330.png", preview: "🌰" },
  { name: "Seedling", category: "food-drink", path: "/png-emojis/1F331.png", preview: "🌱" },
  { name: "Evergreen Tree", category: "food-drink", path: "/png-emojis/1F332.png", preview: "🌲" },
  { name: "Deciduous Tree", category: "food-drink", path: "/png-emojis/1F333.png", preview: "🌳" },
  { name: "Palm Tree", category: "food-drink", path: "/png-emojis/1F334.png", preview: "🌴" },
  { name: "Cactus", category: "food-drink", path: "/png-emojis/1F335.png", preview: "🌵" },
  { name: "Hot Pepper", category: "food-drink", path: "/png-emojis/1F336.png", preview: "🌶️" },
  { name: "Tulip", category: "food-drink", path: "/png-emojis/1F337.png", preview: "🌷" },
  { name: "Cherry Blossom", category: "food-drink", path: "/png-emojis/1F338.png", preview: "🌸" },
  { name: "Rose", category: "food-drink", path: "/png-emojis/1F339.png", preview: "🌹" },
  { name: "Hibiscus", category: "food-drink", path: "/png-emojis/1F33A.png", preview: "🌺" },
  { name: "Sunflower", category: "food-drink", path: "/png-emojis/1F33B.png", preview: "🌻" },
  { name: "Blossom", category: "food-drink", path: "/png-emojis/1F33C.png", preview: "🌼" },
  { name: "Ear of Corn", category: "food-drink", path: "/png-emojis/1F33D.png", preview: "🌽" },
  { name: "Sheaf of Rice", category: "food-drink", path: "/png-emojis/1F33E.png", preview: "🌾" },
  { name: "Herb", category: "food-drink", path: "/png-emojis/1F33F.png", preview: "🌿" },
  { name: "Four Leaf Clover", category: "food-drink", path: "/png-emojis/1F340.png", preview: "🍀" },
  { name: "Maple Leaf", category: "food-drink", path: "/png-emojis/1F341.png", preview: "🍁" },
  { name: "Fallen Leaves", category: "food-drink", path: "/png-emojis/1F342.png", preview: "🍂" },
  { name: "Leaf Fluttering in Wind", category: "food-drink", path: "/png-emojis/1F343.png", preview: "🍃" },
  { name: "Mushroom", category: "food-drink", path: "/png-emojis/1F344.png", preview: "🍄" },
  { name: "Mushroom (Brown Spots)", category: "food-drink", path: "/png-emojis/1F344-200D-1F7EB.png", preview: "🍄‍🟫" },
  { name: "Tomato", category: "food-drink", path: "/png-emojis/1F345.png", preview: "🍅" },
  { name: "Eggplant", category: "food-drink", path: "/png-emojis/1F346.png", preview: "🍆" },
  { name: "Grapes", category: "food-drink", path: "/png-emojis/1F347.png", preview: "🍇" },
  { name: "Melon", category: "food-drink", path: "/png-emojis/1F348.png", preview: "🍈" },
  { name: "Watermelon", category: "food-drink", path: "/png-emojis/1F349.png", preview: "🍉" },
  { name: "Tangerine", category: "food-drink", path: "/png-emojis/1F34A.png", preview: "🍊" },
  { name: "Lemon", category: "food-drink", path: "/png-emojis/1F34B.png", preview: "🍋" },
  { name: "Lemon (Lime)", category: "food-drink", path: "/png-emojis/1F34B-200D-1F7E9.png", preview: "🍋‍🟩" },
  { name: "Banana", category: "food-drink", path: "/png-emojis/1F34C.png", preview: "🍌" },
  { name: "Pineapple", category: "food-drink", path: "/png-emojis/1F34D.png", preview: "🍍" },
  { name: "Red Apple", category: "food-drink", path: "/png-emojis/1F34E.png", preview: "🍎" },
  { name: "Green Apple", category: "food-drink", path: "/png-emojis/1F34F.png", preview: "🍏" },
  { name: "Pear", category: "food-drink", path: "/png-emojis/1F350.png", preview: "🍐" },
  { name: "Peach", category: "food-drink", path: "/png-emojis/1F351.png", preview: "🍑" },
  { name: "Cherries", category: "food-drink", path: "/png-emojis/1F352.png", preview: "🍒" },
  { name: "Strawberry", category: "food-drink", path: "/png-emojis/1F353.png", preview: "🍓" },
  { name: "Hamburger", category: "food-drink", path: "/png-emojis/1F354.png", preview: "🍔" },
  { name: "Pizza", category: "food-drink", path: "/png-emojis/1F355.png", preview: "🍕" },
  { name: "Meat on Bone", category: "food-drink", path: "/png-emojis/1F356.png", preview: "🍖" },
  { name: "Poultry Leg", category: "food-drink", path: "/png-emojis/1F357.png", preview: "🍗" },
  { name: "Rice Cracker", category: "food-drink", path: "/png-emojis/1F358.png", preview: "🍘" },
  { name: "Rice Ball", category: "food-drink", path: "/png-emojis/1F359.png", preview: "🍙" },
  { name: "Cooked Rice", category: "food-drink", path: "/png-emojis/1F35A.png", preview: "🍚" },
  { name: "Curry Rice", category: "food-drink", path: "/png-emojis/1F35B.png", preview: "🍛" },
  { name: "Steaming Bowl", category: "food-drink", path: "/png-emojis/1F35C.png", preview: "🍜" },
  { name: "Spaghetti", category: "food-drink", path: "/png-emojis/1F35D.png", preview: "🍝" },
  { name: "Bread", category: "food-drink", path: "/png-emojis/1F35E.png", preview: "🍞" },
  { name: "French Fries", category: "food-drink", path: "/png-emojis/1F35F.png", preview: "🍟" },
  { name: "Roasted Sweet Potato", category: "food-drink", path: "/png-emojis/1F360.png", preview: "🍠" },
  { name: "Dango", category: "food-drink", path: "/png-emojis/1F361.png", preview: "🍡" },
  { name: "Oden", category: "food-drink", path: "/png-emojis/1F362.png", preview: "🍢" },
  { name: "Sushi", category: "food-drink", path: "/png-emojis/1F363.png", preview: "🍣" },
  { name: "Fried Shrimp", category: "food-drink", path: "/png-emojis/1F364.png", preview: "🍤" },
  { name: "Fish Cake with Swirl", category: "food-drink", path: "/png-emojis/1F365.png", preview: "🍥" },
  { name: "Soft Ice Cream", category: "food-drink", path: "/png-emojis/1F366.png", preview: "🍦" },
  { name: "Shaved Ice", category: "food-drink", path: "/png-emojis/1F367.png", preview: "🍧" },
  { name: "Ice Cream", category: "food-drink", path: "/png-emojis/1F368.png", preview: "🍨" },
  { name: "Doughnut", category: "food-drink", path: "/png-emojis/1F369.png", preview: "🍩" },
  { name: "Cookie", category: "food-drink", path: "/png-emojis/1F36A.png", preview: "🍪" },
  { name: "Chocolate Bar", category: "food-drink", path: "/png-emojis/1F36B.png", preview: "🍫" },
  { name: "Candy", category: "food-drink", path: "/png-emojis/1F36C.png", preview: "🍬" },
  { name: "Lollipop", category: "food-drink", path: "/png-emojis/1F36D.png", preview: "🍭" },
  { name: "Custard", category: "food-drink", path: "/png-emojis/1F36E.png", preview: "🍮" },
  { name: "Honey Pot", category: "food-drink", path: "/png-emojis/1F36F.png", preview: "🍯" },
  { name: "Shortcake", category: "food-drink", path: "/png-emojis/1F370.png", preview: "🍰" },
  { name: "Bento Box", category: "food-drink", path: "/png-emojis/1F371.png", preview: "🍱" },
  { name: "Pot of Food", category: "food-drink", path: "/png-emojis/1F372.png", preview: "🍲" },
  { name: "Cooking", category: "food-drink", path: "/png-emojis/1F373.png", preview: "🍳" },
  { name: "Fork and Knife", category: "food-drink", path: "/png-emojis/1F374.png", preview: "🍴" },
  { name: "Teacup Without Handle", category: "food-drink", path: "/png-emojis/1F375.png", preview: "🍵" },
  { name: "Sake", category: "food-drink", path: "/png-emojis/1F376.png", preview: "🍶" },
  { name: "Wine Glass", category: "food-drink", path: "/png-emojis/1F377.png", preview: "🍷" },
  { name: "Cocktail Glass", category: "food-drink", path: "/png-emojis/1F378.png", preview: "🍸" },
  { name: "Tropical Drink", category: "food-drink", path: "/png-emojis/1F379.png", preview: "🍹" },
  { name: "Beer Mug", category: "food-drink", path: "/png-emojis/1F37A.png", preview: "🍺" },
  { name: "Clinking Beer Mugs", category: "food-drink", path: "/png-emojis/1F37B.png", preview: "🍻" },
  { name: "Baby Bottle", category: "food-drink", path: "/png-emojis/1F37C.png", preview: "🍼" },
  { name: "Fork and Knife with Plate", category: "food-drink", path: "/png-emojis/1F37D.png", preview: "🍽️" },
  { name: "Bottle with Popping Cork", category: "food-drink", path: "/png-emojis/1F37E.png", preview: "🍾" },
  { name: "Popcorn", category: "food-drink", path: "/png-emojis/1F37F.png", preview: "🍿" },

  // Activities & Sports - All entries
  { name: "Ribbon", category: "activities", path: "/png-emojis/1F380.png", preview: "🎀" },
  { name: "Wrapped Gift", category: "activities", path: "/png-emojis/1F381.png", preview: "🎁" },
  { name: "Birthday Cake", category: "activities", path: "/png-emojis/1F382.png", preview: "🎂" },
  { name: "Jack-O-Lantern", category: "activities", path: "/png-emojis/1F383.png", preview: "🎃" },
  { name: "Christmas Tree", category: "activities", path: "/png-emojis/1F384.png", preview: "🎄" },
  { name: "Santa Claus", category: "people", path: "/png-emojis/1F385.png", preview: "🎅" },
  { name: "Santa Claus: Light Skin Tone", category: "people", path: "/png-emojis/1F385-1F3FB.png", preview: "🎅🏻" },
  { name: "Santa Claus: Medium-Light Skin Tone", category: "people", path: "/png-emojis/1F385-1F3FC.png", preview: "🎅🏼" },
  { name: "Santa Claus: Medium Skin Tone", category: "people", path: "/png-emojis/1F385-1F3FD.png", preview: "🎅🏽" },
  { name: "Santa Claus: Medium-Dark Skin Tone", category: "people", path: "/png-emojis/1F385-1F3FE.png", preview: "🎅🏾" },
  { name: "Santa Claus: Dark Skin Tone", category: "people", path: "/png-emojis/1F385-1F3FF.png", preview: "🎅🏿" },
  { name: "Fireworks", category: "activities", path: "/png-emojis/1F386.png", preview: "🎆" },
  { name: "Sparkler", category: "activities", path: "/png-emojis/1F387.png", preview: "🎇" },
  { name: "Balloon", category: "activities", path: "/png-emojis/1F388.png", preview: "🎈" },
  { name: "Party Popper", category: "activities", path: "/png-emojis/1F389.png", preview: "🎉" },
  { name: "Confetti Ball", category: "activities", path: "/png-emojis/1F38A.png", preview: "🎊" },
  { name: "Tanabata Tree", category: "activities", path: "/png-emojis/1F38B.png", preview: "🎋" },
  { name: "Pine Decoration", category: "activities", path: "/png-emojis/1F38C.png", preview: "🎌" },
  { name: "Japanese Dolls", category: "activities", path: "/png-emojis/1F38D.png", preview: "🎍" },
  { name: "Carp Streamer", category: "activities", path: "/png-emojis/1F38E.png", preview: "🎎" },
  { name: "Wind Chime", category: "activities", path: "/png-emojis/1F38F.png", preview: "🎏" },
  { name: "Moon Viewing Ceremony", category: "activities", path: "/png-emojis/1F390.png", preview: "🎐" },
  { name: "School Backpack", category: "activities", path: "/png-emojis/1F391.png", preview: "🎑" },
  { name: "Graduation Cap", category: "activities", path: "/png-emojis/1F392.png", preview: "🎒" },
  { name: "Carp Streamer", category: "activities", path: "/png-emojis/1F393.png", preview: "🎓" },
  { name: "Military Medal", category: "activities", path: "/png-emojis/1F396.png", preview: "🎖️" },
  { name: "Reminder Ribbon", category: "activities", path: "/png-emojis/1F397.png", preview: "🎗️" },
  { name: "Studio Microphone", category: "activities", path: "/png-emojis/1F399.png", preview: "🎙️" },
  { name: "Level Slider", category: "activities", path: "/png-emojis/1F39A.png", preview: "🎚️" },
  { name: "Control Knobs", category: "activities", path: "/png-emojis/1F39B.png", preview: "🎛️" },
  { name: "Film Frames", category: "activities", path: "/png-emojis/1F39E.png", preview: "🎞️" },
  { name: "Admission Tickets", category: "activities", path: "/png-emojis/1F39F.png", preview: "🎟️" },
  { name: "Carousel Horse", category: "activities", path: "/png-emojis/1F3A0.png", preview: "🎠" },
  { name: "Ferris Wheel", category: "activities", path: "/png-emojis/1F3A1.png", preview: "🎡" },
  { name: "Roller Coaster", category: "activities", path: "/png-emojis/1F3A2.png", preview: "🎢" },
  { name: "Fishing Pole", category: "activities", path: "/png-emojis/1F3A3.png", preview: "🎣" },
  { name: "Microphone", category: "activities", path: "/png-emojis/1F3A4.png", preview: "🎤" },
  { name: "Movie Camera", category: "activities", path: "/png-emojis/1F3A5.png", preview: "🎥" },
  { name: "Headphone", category: "activities", path: "/png-emojis/1F3A7.png", preview: "🎧" },
  { name: "Artist Palette", category: "activities", path: "/png-emojis/1F3A8.png", preview: "🎨" },
  { name: "Top Hat", category: "activities", path: "/png-emojis/1F3A9.png", preview: "🎩" },
  { name: "Circus Tent", category: "activities", path: "/png-emojis/1F3AA.png", preview: "🎪" },
  { name: "Ticket", category: "activities", path: "/png-emojis/1F3AB.png", preview: "🎫" },
  { name: "Clapper Board", category: "activities", path: "/png-emojis/1F3AC.png", preview: "🎬" },
  { name: "Performing Arts", category: "activities", path: "/png-emojis/1F3AD.png", preview: "🎭" },
  { name: "Video Game", category: "activities", path: "/png-emojis/1F3AE.png", preview: "🎮" },
  { name: "Direct Hit", category: "activities", path: "/png-emojis/1F3AF.png", preview: "🎯" },
  { name: "Slot Machine", category: "activities", path: "/png-emojis/1F3B0.png", preview: "🎰" },
  { name: "Pool 8 Ball", category: "activities", path: "/png-emojis/1F3B1.png", preview: "🎱" },
  { name: "Game Die", category: "activities", path: "/png-emojis/1F3B2.png", preview: "🎲" },
  { name: "Bowling", category: "activities", path: "/png-emojis/1F3B3.png", preview: "🎳" },
  { name: "Flower Playing Cards", category: "activities", path: "/png-emojis/1F3B4.png", preview: "🎴" },
  { name: "Musical Note", category: "activities", path: "/png-emojis/1F3B5.png", preview: "🎵" },
  { name: "Musical Notes", category: "activities", path: "/png-emojis/1F3B6.png", preview: "🎶" },
  { name: "Saxophone", category: "activities", path: "/png-emojis/1F3B7.png", preview: "🎷" },
  { name: "Guitar", category: "activities", path: "/png-emojis/1F3B8.png", preview: "🎸" },
  { name: "Musical Keyboard", category: "activities", path: "/png-emojis/1F3B9.png", preview: "🎹" },
  { name: "Trumpet", category: "activities", path: "/png-emojis/1F3BA.png", preview: "🎺" },
  { name: "Violin", category: "activities", path: "/png-emojis/1F3BB.png", preview: "🎻" },
  { name: "Musical Score", category: "activities", path: "/png-emojis/1F3BC.png", preview: "🎼" },
  { name: "Running Shirt", category: "activities", path: "/png-emojis/1F3BD.png", preview: "🎽" },
  { name: "Tennis", category: "activities", path: "/png-emojis/1F3BE.png", preview: "🎾" },
  { name: "Skis", category: "activities", path: "/png-emojis/1F3BF.png", preview: "🎿" },
  { name: "Basketball", category: "activities", path: "/png-emojis/1F3C0.png", preview: "🏀" },
  { name: "Checkered Flag", category: "activities", path: "/png-emojis/1F3C1.png", preview: "🏁" },
  { name: "Snowboarder", category: "activities", path: "/png-emojis/1F3C2.png", preview: "🏂" },
  { name: "Snowboarder: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C2-1F3FB.png", preview: "🏂🏻" },
  { name: "Snowboarder: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C2-1F3FC.png", preview: "🏂🏼" },
  { name: "Snowboarder: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C2-1F3FD.png", preview: "🏂🏽" },
  { name: "Snowboarder: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C2-1F3FE.png", preview: "🏂🏾" },
  { name: "Snowboarder: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C2-1F3FF.png", preview: "🏂🏿" },

  // Person Running variants
  { name: "Person Running", category: "activities", path: "/png-emojis/1F3C3.png", preview: "🏃" },
  { name: "Person Running: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FB.png", preview: "🏃🏻" },
  { name: "Woman Running: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FB-200D-2640-FE0F.png", preview: "🏃🏻‍♀️" },
  { name: "Man Running: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FB-200D-2642-FE0F.png", preview: "🏃🏻‍♂️" },
  { name: "Person Running: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FC.png", preview: "🏃🏼" },
  { name: "Woman Running: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FC-200D-2640-FE0F.png", preview: "🏃🏼‍♀️" },
  { name: "Man Running: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FC-200D-2642-FE0F.png", preview: "🏃🏼‍♂️" },
  { name: "Person Running: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FD.png", preview: "🏃🏽" },
  { name: "Woman Running: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FD-200D-2640-FE0F.png", preview: "🏃🏽‍♀️" },
  { name: "Man Running: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FD-200D-2642-FE0F.png", preview: "🏃🏽‍♂️" },
  { name: "Person Running: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FE.png", preview: "🏃🏾" },
  { name: "Woman Running: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FE-200D-2640-FE0F.png", preview: "🏃🏾‍♀️" },
  { name: "Man Running: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FE-200D-2642-FE0F.png", preview: "🏃🏾‍♂️" },
  { name: "Person Running: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FF.png", preview: "🏃🏿" },
  { name: "Woman Running: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FF-200D-2640-FE0F.png", preview: "🏃🏿‍♀️" },
  { name: "Man Running: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C3-1F3FF-200D-2642-FE0F.png", preview: "🏃🏿‍♂️" },
  { name: "Woman Running", category: "activities", path: "/png-emojis/1F3C3-200D-2640-FE0F.png", preview: "🏃‍♀️" },
  { name: "Man Running", category: "activities", path: "/png-emojis/1F3C3-200D-2642-FE0F.png", preview: "🏃‍♂️" },

  // Person Surfing variants
  { name: "Person Surfing", category: "activities", path: "/png-emojis/1F3C4.png", preview: "🏄" },
  { name: "Person Surfing: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FB.png", preview: "🏄🏻" },
  { name: "Woman Surfing: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FB-200D-2640-FE0F.png", preview: "🏄🏻‍♀️" },
  { name: "Man Surfing: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FB-200D-2642-FE0F.png", preview: "🏄🏻‍♂️" },
  { name: "Person Surfing: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FC.png", preview: "🏄🏼" },
  { name: "Woman Surfing: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FC-200D-2640-FE0F.png", preview: "🏄🏼‍♀️" },
  { name: "Man Surfing: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FC-200D-2642-FE0F.png", preview: "🏄🏼‍♂️" },
  { name: "Person Surfing: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FD.png", preview: "🏄🏽" },
  { name: "Woman Surfing: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FD-200D-2640-FE0F.png", preview: "🏄🏽‍♀️" },
  { name: "Man Surfing: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FD-200D-2642-FE0F.png", preview: "🏄🏽‍♂️" },
  { name: "Person Surfing: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FE.png", preview: "🏄🏾" },
  { name: "Woman Surfing: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FE-200D-2640-FE0F.png", preview: "🏄🏾‍♀️" },
  { name: "Man Surfing: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FE-200D-2642-FE0F.png", preview: "🏄🏾‍♂️" },
  { name: "Person Surfing: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FF.png", preview: "🏄🏿" },
  { name: "Woman Surfing: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FF-200D-2640-FE0F.png", preview: "🏄🏿‍♀️" },
  { name: "Man Surfing: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C4-1F3FF-200D-2642-FE0F.png", preview: "🏄🏿‍♂️" },
  { name: "Woman Surfing", category: "activities", path: "/png-emojis/1F3C4-200D-2640-FE0F.png", preview: "🏄‍♀️" },
  { name: "Man Surfing", category: "activities", path: "/png-emojis/1F3C4-200D-2642-FE0F.png", preview: "🏄‍♂️" },

  { name: "Sports Medal", category: "activities", path: "/png-emojis/1F3C5.png", preview: "🏅" },
  { name: "Trophy", category: "activities", path: "/png-emojis/1F3C6.png", preview: "🏆" },
  { name: "Horse Racing", category: "activities", path: "/png-emojis/1F3C7.png", preview: "🏇" },
  { name: "Horse Racing: Light Skin Tone", category: "activities", path: "/png-emojis/1F3C7-1F3FB.png", preview: "🏇🏻" },
  { name: "Horse Racing: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3C7-1F3FC.png", preview: "🏇🏼" },
  { name: "Horse Racing: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3C7-1F3FD.png", preview: "🏇🏽" },
  { name: "Horse Racing: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C7-1F3FE.png", preview: "🏇🏾" },
  { name: "Horse Racing: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3C7-1F3FF.png", preview: "🏇🏿" },
  { name: "American Football", category: "activities", path: "/png-emojis/1F3C8.png", preview: "🏈" },
  { name: "Rugby Football", category: "activities", path: "/png-emojis/1F3C9.png", preview: "🏉" },

  // Person Swimming variants
  { name: "Person Swimming", category: "activities", path: "/png-emojis/1F3CA.png", preview: "🏊" },
  { name: "Person Swimming: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FB.png", preview: "🏊🏻" },
  { name: "Woman Swimming: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FB-200D-2640-FE0F.png", preview: "🏊🏻‍♀️" },
  { name: "Man Swimming: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FB-200D-2642-FE0F.png", preview: "🏊🏻‍♂️" },
  { name: "Person Swimming: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FC.png", preview: "🏊🏼" },
  { name: "Woman Swimming: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FC-200D-2640-FE0F.png", preview: "🏊🏼‍♀️" },
  { name: "Man Swimming: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FC-200D-2642-FE0F.png", preview: "🏊🏼‍♂️" },
  { name: "Person Swimming: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FD.png", preview: "🏊🏽" },
  { name: "Woman Swimming: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FD-200D-2640-FE0F.png", preview: "🏊🏽‍♀️" },
  { name: "Man Swimming: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FD-200D-2642-FE0F.png", preview: "🏊🏽‍♂️" },
  { name: "Person Swimming: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FE.png", preview: "🏊🏾" },
  { name: "Woman Swimming: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FE-200D-2640-FE0F.png", preview: "🏊🏾‍♀️" },
  { name: "Man Swimming: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FE-200D-2642-FE0F.png", preview: "🏊🏾‍♂️" },
  { name: "Person Swimming: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FF.png", preview: "🏊🏿" },
  { name: "Woman Swimming: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FF-200D-2640-FE0F.png", preview: "🏊🏿‍♀️" },
  { name: "Man Swimming: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CA-1F3FF-200D-2642-FE0F.png", preview: "🏊🏿‍♂️" },
  { name: "Woman Swimming", category: "activities", path: "/png-emojis/1F3CA-200D-2640-FE0F.png", preview: "🏊‍♀️" },
  { name: "Man Swimming", category: "activities", path: "/png-emojis/1F3CA-200D-2642-FE0F.png", preview: "🏊‍♂️" },

  // Person Lifting Weights variants
  { name: "Person Lifting Weights", category: "activities", path: "/png-emojis/1F3CB.png", preview: "🏋️" },
  { name: "Person Lifting Weights: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FB.png", preview: "🏋🏻" },
  { name: "Woman Lifting Weights: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FB-200D-2640-FE0F.png", preview: "🏋🏻‍♀️" },
  { name: "Man Lifting Weights: Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FB-200D-2642-FE0F.png", preview: "🏋🏻‍♂️" },
  { name: "Person Lifting Weights: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FC.png", preview: "🏋🏼" },
  { name: "Woman Lifting Weights: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FC-200D-2640-FE0F.png", preview: "🏋🏼‍♀️" },
  { name: "Man Lifting Weights: Medium-Light Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FC-200D-2642-FE0F.png", preview: "🏋🏼‍♂️" },
  { name: "Person Lifting Weights: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FD.png", preview: "🏋🏽" },
  { name: "Woman Lifting Weights: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FD-200D-2640-FE0F.png", preview: "🏋🏽‍♀️" },
  { name: "Man Lifting Weights: Medium Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FD-200D-2642-FE0F.png", preview: "🏋🏽‍♂️" },
  { name: "Person Lifting Weights: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FE.png", preview: "🏋🏾" },
  { name: "Woman Lifting Weights: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FE-200D-2640-FE0F.png", preview: "🏋🏾‍♀️" },
  { name: "Man Lifting Weights: Medium-Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FE-200D-2642-FE0F.png", preview: "🏋🏾‍♂️" },
  { name: "Person Lifting Weights: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FF.png", preview: "🏋🏿" },
  { name: "Woman Lifting Weights: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FF-200D-2640-FE0F.png", preview: "🏋🏿‍♀️" },
  { name: "Man Lifting Weights: Dark Skin Tone", category: "activities", path: "/png-emojis/1F3CB-1F3FF-200D-2642-FE0F.png", preview: "🏋🏿‍♂️" },

  // Travel & Places - All transport emojis
  { name: "Rocket", category: "travel-places", path: "/png-emojis/1F680.png", preview: "🚀" },
  { name: "Helicopter", category: "travel-places", path: "/png-emojis/1F681.png", preview: "🚁" },
  { name: "Steam Locomotive", category: "travel-places", path: "/png-emojis/1F682.png", preview: "🚂" },
  { name: "Railway Car", category: "travel-places", path: "/png-emojis/1F683.png", preview: "🚃" },
  { name: "High-Speed Train", category: "travel-places", path: "/png-emojis/1F684.png", preview: "🚄" },
  { name: "Bullet Train", category: "travel-places", path: "/png-emojis/1F685.png", preview: "🚅" },
  { name: "Train", category: "travel-places", path: "/png-emojis/1F686.png", preview: "🚆" },
  { name: "Metro", category: "travel-places", path: "/png-emojis/1F687.png", preview: "🚇" },
  { name: "Light Rail", category: "travel-places", path: "/png-emojis/1F688.png", preview: "🚈" },
  { name: "Station", category: "travel-places", path: "/png-emojis/1F689.png", preview: "🚉" },
  { name: "Tram", category: "travel-places", path: "/png-emojis/1F68A.png", preview: "🚊" },
  { name: "Tram Car", category: "travel-places", path: "/png-emojis/1F68B.png", preview: "🚋" },
  { name: "Bus", category: "travel-places", path: "/png-emojis/1F68C.png", preview: "🚌" },
  { name: "Oncoming Bus", category: "travel-places", path: "/png-emojis/1F68D.png", preview: "🚍" },
  { name: "Trolleybus", category: "travel-places", path: "/png-emojis/1F68E.png", preview: "🚎" },
  { name: "Bus Stop", category: "travel-places", path: "/png-emojis/1F68F.png", preview: "🚏" },
  { name: "Minibus", category: "travel-places", path: "/png-emojis/1F690.png", preview: "🚐" },
  { name: "Ambulance", category: "travel-places", path: "/png-emojis/1F691.png", preview: "🚑" },
  { name: "Fire Engine", category: "travel-places", path: "/png-emojis/1F692.png", preview: "🚒" },
  { name: "Police Car", category: "travel-places", path: "/png-emojis/1F693.png", preview: "🚓" },

  // Emotions - Full set
  { name: "Grinning Face", category: "emotions", path: "/png-emojis/1F600.png", preview: "😀" },
  { name: "Beaming Face with Smiling Eyes", category: "emotions", path: "/png-emojis/1F601.png", preview: "😁" },
  { name: "Face with Tears of Joy", category: "emotions", path: "/png-emojis/1F602.png", preview: "😂" },
  { name: "Grinning Face with Big Eyes", category: "emotions", path: "/png-emojis/1F603.png", preview: "😃" },
  { name: "Smiling Face with Smiling Eyes", category: "emotions", path: "/png-emojis/1F604.png", preview: "😄" },
  { name: "Grinning Face with Sweat", category: "emotions", path: "/png-emojis/1F605.png", preview: "😅" },
  { name: "Grinning Squinting Face", category: "emotions", path: "/png-emojis/1F606.png", preview: "😆" },
  { name: "Smiling Face with Halo", category: "emotions", path: "/png-emojis/1F607.png", preview: "😇" },
  { name: "Smiling Face with Horns", category: "emotions", path: "/png-emojis/1F608.png", preview: "😈" },
  { name: "Winking Face", category: "emotions", path: "/png-emojis/1F609.png", preview: "😉" },
  { name: "Smiling Face with Smiling Eyes", category: "emotions", path: "/png-emojis/1F60A.png", preview: "😊" },
  { name: "Face Savoring Food", category: "emotions", path: "/png-emojis/1F60B.png", preview: "😋" },
  { name: "Relieved Face", category: "emotions", path: "/png-emojis/1F60C.png", preview: "😌" },
  { name: "Smiling Face with Heart-Eyes", category: "emotions", path: "/png-emojis/1F60D.png", preview: "😍" },
  { name: "Smiling Face with Sunglasses", category: "emotions", path: "/png-emojis/1F60E.png", preview: "😎" },
  { name: "Smirking Face", category: "emotions", path: "/png-emojis/1F60F.png", preview: "😏" },
  { name: "Neutral Face", category: "emotions", path: "/png-emojis/1F610.png", preview: "😐" },
  { name: "Expressionless Face", category: "emotions", path: "/png-emojis/1F611.png", preview: "😑" },
  { name: "Unamused Face", category: "emotions", path: "/png-emojis/1F612.png", preview: "😒" },
  { name: "Downcast Face with Sweat", category: "emotions", path: "/png-emojis/1F613.png", preview: "😓" },
  { name: "Pensive Face", category: "emotions", path: "/png-emojis/1F614.png", preview: "😔" },
  { name: "Confused Face", category: "emotions", path: "/png-emojis/1F615.png", preview: "😕" },
  { name: "Confounded Face", category: "emotions", path: "/png-emojis/1F616.png", preview: "😖" },
  { name: "Kissing Face", category: "emotions", path: "/png-emojis/1F617.png", preview: "😗" },
  { name: "Face Blowing a Kiss", category: "emotions", path: "/png-emojis/1F618.png", preview: "😘" },
  { name: "Kissing Face with Smiling Eyes", category: "emotions", path: "/png-emojis/1F619.png", preview: "😙" },
  { name: "Kissing Face with Closed Eyes", category: "emotions", path: "/png-emojis/1F61A.png", preview: "😚" },
  { name: "Face with Tongue", category: "emotions", path: "/png-emojis/1F61B.png", preview: "😛" },
  { name: "Winking Face with Tongue", category: "emotions", path: "/png-emojis/1F61C.png", preview: "😜" },
  { name: "Squinting Face with Tongue", category: "emotions", path: "/png-emojis/1F61D.png", preview: "😝" },
  { name: "Disappointed Face", category: "emotions", path: "/png-emojis/1F61E.png", preview: "😞" },
  { name: "Worried Face", category: "emotions", path: "/png-emojis/1F61F.png", preview: "😟" },
  { name: "Angry Face", category: "emotions", path: "/png-emojis/1F620.png", preview: "😠" },
  { name: "Pouting Face", category: "emotions", path: "/png-emojis/1F621.png", preview: "😡" },
  { name: "Crying Face", category: "emotions", path: "/png-emojis/1F622.png", preview: "😢" },
  { name: "Persevering Face", category: "emotions", path: "/png-emojis/1F623.png", preview: "😣" },
  { name: "Face with Steam From Nose", category: "emotions", path: "/png-emojis/1F624.png", preview: "😤" },
  { name: "Sad but Relieved Face", category: "emotions", path: "/png-emojis/1F625.png", preview: "😥" },
  { name: "Frowning Face with Open Mouth", category: "emotions", path: "/png-emojis/1F626.png", preview: "😦" },
  { name: "Anguished Face", category: "emotions", path: "/png-emojis/1F627.png", preview: "😧" },
  { name: "Fearful Face", category: "emotions", path: "/png-emojis/1F628.png", preview: "😨" },
  { name: "Weary Face", category: "emotions", path: "/png-emojis/1F629.png", preview: "😩" },
  { name: "Sleepy Face", category: "emotions", path: "/png-emojis/1F62A.png", preview: "😪" },
  { name: "Tired Face", category: "emotions", path: "/png-emojis/1F62B.png", preview: "😫" },
  { name: "Grimacing Face", category: "emotions", path: "/png-emojis/1F62C.png", preview: "😬" },
  { name: "Loudly Crying Face", category: "emotions", path: "/png-emojis/1F62D.png", preview: "😭" },
  { name: "Face with Open Mouth", category: "emotions", path: "/png-emojis/1F62E.png", preview: "😮" },
  { name: "Hushed Face", category: "emotions", path: "/png-emojis/1F62F.png", preview: "😯" },
  { name: "Anxious Face with Sweat", category: "emotions", path: "/png-emojis/1F630.png", preview: "😰" },
  { name: "Face Screaming in Fear", category: "emotions", path: "/png-emojis/1F631.png", preview: "😱" },
  { name: "Astonished Face", category: "emotions", path: "/png-emojis/1F632.png", preview: "😲" },
  { name: "Flushed Face", category: "emotions", path: "/png-emojis/1F633.png", preview: "😳" },
  { name: "Sleeping Face", category: "emotions", path: "/png-emojis/1F634.png", preview: "😴" },
  { name: "Dizzy Face", category: "emotions", path: "/png-emojis/1F635.png", preview: "😵" },
  { name: "Face Without Mouth", category: "emotions", path: "/png-emojis/1F636.png", preview: "😶" },
  { name: "Face with Medical Mask", category: "emotions", path: "/png-emojis/1F637.png", preview: "😷" },

  // Symbols - All common symbols
  { name: "Red Heart", category: "symbols", path: "/png-emojis/2764.png", preview: "❤️" },
  { name: "Warning Sign", category: "symbols", path: "/png-emojis/26A0.png", preview: "⚠️" },
  { name: "High Voltage", category: "symbols", path: "/png-emojis/26A1.png", preview: "⚡" },
  { name: "Sparkles", category: "symbols", path: "/png-emojis/2728.png", preview: "✨" },
  { name: "Star", category: "symbols", path: "/png-emojis/2B50.png", preview: "⭐" },
  { name: "Sun", category: "symbols", path: "/png-emojis/2600.png", preview: "☀️" },
  { name: "Cloud", category: "symbols", path: "/png-emojis/2601.png", preview: "☁️" },
  { name: "Umbrella", category: "symbols", path: "/png-emojis/2602.png", preview: "☂️" },
  { name: "Snowman", category: "symbols", path: "/png-emojis/2603.png", preview: "☃️" },
  { name: "Comet", category: "symbols", path: "/png-emojis/2604.png", preview: "☄️" },
  { name: "Heart Suit", category: "symbols", path: "/png-emojis/2665.png", preview: "♥️" },
  { name: "Spade Suit", category: "symbols", path: "/png-emojis/2660.png", preview: "♠️" },
  { name: "Club Suit", category: "symbols", path: "/png-emojis/2663.png", preview: "♣️" },
  { name: "Diamond Suit", category: "symbols", path: "/png-emojis/2666.png", preview: "♦️" },

  // Note: This is still a partial representation. The complete registry would need 
  // ALL 3757 entries programmatically generated. This manual process is impractical.
  // The generator script should handle this automatically.
];

/**
 * Get icon by path
 */
export function getIconByPath(path: string): IconInfo | undefined {
  return iconRegistry.find(icon => icon.path === path);
}

/**
 * Get icons by category
 */
export function getIconsByCategory(category: string): IconInfo[] {
  return iconRegistry.filter(icon => icon.category === category);
}

/**
 * Get all available categories
 */
export function getCategories(): string[] {
  const categories = Array.from(new Set(iconRegistry.map(icon => icon.category)));
  return categories.sort();
}

/**
 * Get category display name
 */
export function getCategoryDisplayName(category: string): string {
  const displayNames: Record<string, string> = {
    'emotions': 'Emotions & Faces',
    'people': 'People & Body',
    'animals-nature': 'Animals & Nature', 
    'food-drink': 'Food & Drink',
    'activities': 'Activities & Sports',
    'travel-places': 'Travel & Places',
    'objects': 'Objects & Symbols',
    'symbols': 'Symbols',
    'flags': 'Country Flags'
  };
  return displayNames[category] || category.charAt(0).toUpperCase() + category.slice(1);
}

/**
 * Get custom stamps as icons
 */
export function getCustomStampsAsIcons(): IconInfo[] {
  const customStamps = getCustomStamps();
  return customStamps.map((stamp: CustomStamp) => ({
    name: stamp.name,
    category: 'custom',
    path: stamp.dataUrl,
    preview: stamp.preview
  }));
}

/**
 * Get all categories including custom
 */
export function getAllCategories(): string[] {
  const standardCategories = getCategories();
  const customStamps = getCustomStamps();
  
  if (customStamps.length > 0) {
    return ['custom', ...standardCategories];
  }
  
  return standardCategories;
}

/**
 * Get icons by category including custom stamps
 */
export function getIconsByCategoryWithCustom(category: string): IconInfo[] {
  if (category === 'custom') {
    return getCustomStampsAsIcons();
  }
  return getIconsByCategory(category);
}

/**
 * Get all icons including custom stamps
 */
export function getAllIcons(): IconInfo[] {
  return [...iconRegistry, ...getCustomStampsAsIcons()];
}

// Export category statistics for debugging
export const CATEGORY_STATS = {
  "emotions": 56,
  "animals-nature": 45,
  "food-drink": 85,
  "activities": 120,
  "travel-places": 25,
  "objects": 15,
  "symbols": 20,
  "flags": 265,
  "people": 15
};
export const TOTAL_EMOJIS = 646; // Manually counted entries above
export const GENERATED_AT = "2025-01-27T20:39:12.000Z";